"""Generate farm_loop/pseo_data_batch_a.py from a workflow dataset result file.

The four reference datasets (HTTP status codes, file-extension MIME types, HTTP
headers, exit codes & signals) were produced by a parallel agent workflow and
saved as JSON. This script validates a few known anchors and emits a clean,
reviewable Python data module so the page builders consume vetted constants.

Usage: python scripts/gen_pseo_data.py <workflow_output.json>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def _load_result(path: str) -> dict:
    obj = json.loads(Path(path).read_text(encoding="utf-8"))
    return obj.get("result", obj)


def _check(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"validation failed: {message}")


def main() -> int:
    src = sys.argv[1]
    data = _load_result(src)

    http = data["http_status"]
    mime = data["mime_types"]
    headers = data["http_headers"]
    exits = data["exit_signals"]

    # Sanity-check well-known anchors so a bad generation can't ship silently.
    _check(any(e["code"] == 404 and e["name"] == "Not Found" for e in http), "HTTP 404 Not Found")
    _check(any(e["code"] == 200 and e["name"] == "OK" for e in http), "HTTP 200 OK")
    _check(any(e["code"] == 500 for e in http), "HTTP 500 present")
    _check(any(e["ext"] == "json" and e["mime"] == "application/json" for e in mime), ".json -> application/json")
    _check(any(e["ext"] == "png" and e["mime"] == "image/png" for e in mime), ".png -> image/png")
    _check(any(e["name"] == "Content-Type" for e in headers), "Content-Type header")
    _check(any(e["name"] == "Cache-Control" for e in headers), "Cache-Control header")
    _check(any(e["kind"] == "signal" and e["label"] == "SIGKILL" and e["number"] == 9 for e in exits), "SIGKILL=9")
    _check(any(e["kind"] == "exit" and e["number"] == 137 for e in exits), "exit code 137")

    def dump(name: str, rows: list) -> str:
        body = json.dumps(rows, indent=4, ensure_ascii=False)
        return f"{name} = {body}\n"

    out = Path("farm_loop/pseo_data_batch_a.py")
    header = (
        '"""Vetted reference datasets for pSEO clusters (HTTP status codes, MIME\n'
        "types, HTTP headers, exit codes & signals). Generated by\n"
        "scripts/gen_pseo_data.py from a parallel-agent workflow and anchor-validated.\n"
        'Do not hand-edit; regenerate from the workflow output instead."""\n'
        "from __future__ import annotations\n\n"
    )
    out.write_text(
        header
        + dump("HTTP_STATUS", http) + "\n"
        + dump("MIME_TYPES", mime) + "\n"
        + dump("HTTP_HEADERS", headers) + "\n"
        + dump("EXIT_SIGNALS", exits),
        encoding="utf-8",
    )
    print(
        f"wrote {out}: {len(http)} status codes, {len(mime)} mime types, "
        f"{len(headers)} headers, {len(exits)} exit/signals"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
