"""Generate farm_loop/pseo_data_more.py from the CSS/HTML/lang/airport workflow.

Validates known anchors before emitting the vetted datasets the page builders
consume. Usage: python scripts/gen_pseo_more.py <workflow_output.json>
"""
from __future__ import annotations

import html
import json
import sys
from pathlib import Path


def _load_result(path: str) -> dict:
    obj = json.loads(Path(path).read_text(encoding="utf-8"))
    return obj.get("result", obj)


def _clean(rows: list) -> list:
    # Agents sometimes pre-escape HTML entities (&lt; &amp; ...) in syntax/example
    # fields. Store raw so the page builder's escape() renders correctly.
    return [
        {key: (html.unescape(value) if isinstance(value, str) else value) for key, value in row.items()}
        for row in rows
    ]


def _check(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"validation failed: {message}")


def main() -> int:
    data = _load_result(sys.argv[1])
    css = _clean(data["css"])
    html_tags = _clean(data["html"])
    languages = _clean(data["languages"])
    airports = _clean(data["airports"])

    _check(len(css) >= 180, "180+ CSS properties")
    _check(any(e["name"] == "flex-grow" for e in css), "flex-grow property")
    _check(len(html_tags) >= 90, "90+ HTML tags")
    _check(any(e["name"] == "details" for e in html_tags), "details tag")
    _check(any(e["code"] == "es" and "Spanish" in e["name"] for e in languages), "es = Spanish")
    _check(any(e["iata"] == "LAX" for e in airports), "LAX airport")

    def dump(name: str, rows: list) -> str:
        return f"{name} = {json.dumps(rows, indent=4, ensure_ascii=False)}\n"

    out = Path("farm_loop/pseo_data_more.py")
    header = (
        '"""Vetted CSS properties, HTML tags, ISO 639-1 languages, and major airport\n'
        "datasets for pSEO clusters. Generated by scripts/gen_pseo_more.py from a\n"
        'parallel-agent workflow and anchor-validated. Do not hand-edit."""\n'
        "from __future__ import annotations\n\n"
    )
    out.write_text(
        header
        + dump("CSS_PROPERTIES", css) + "\n"
        + dump("HTML_TAGS", html_tags) + "\n"
        + dump("LANGUAGES", languages) + "\n"
        + dump("AIRPORTS", airports),
        encoding="utf-8",
    )
    print(
        f"wrote {out}: {len(css)} css, {len(html_tags)} html, "
        f"{len(languages)} languages, {len(airports)} airports"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
