"""Generate farm_loop/pseo_data_devref.py from the dev-reference workflow result.

Validates known anchors (git reset --soft, an email regex, chmod) before emitting
the vetted Git / regex / Linux datasets the page builders consume.

Usage: python scripts/gen_pseo_devref.py <workflow_output.json>
"""
from __future__ import annotations

import html
import json
import sys
from pathlib import Path


def _load_result(path: str) -> dict:
    obj = json.loads(Path(path).read_text(encoding="utf-8"))
    return obj.get("result", obj)


def _clean(rows: list) -> list:
    # The generator agent sometimes pre-escapes HTML entities (&lt; &amp; ...) in
    # commands. Store the raw text so the page builder's escape() renders correctly
    # instead of double-escaping.
    return [
        {key: (html.unescape(value) if isinstance(value, str) else value) for key, value in row.items()}
        for row in rows
    ]


def _check(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"validation failed: {message}")


def main() -> int:
    data = _load_result(sys.argv[1])
    git = _clean(data["git"])
    regex = _clean(data["regex"])
    linux = _clean(data["linux"])

    _check(len(git) >= 40, "at least 40 git recipes")
    _check(any("reset" in e["command"] for e in git), "a git reset recipe")
    _check(len(regex) >= 30, "at least 30 regex patterns")
    _check(any("email" in e["name"].lower() for e in regex), "an email regex")
    _check(len(linux) >= 45, "at least 45 linux commands")
    _check(any("chmod" in e["command"] or "chmod" in e["name"].lower() for e in linux), "a chmod command")

    def dump(name: str, rows: list) -> str:
        return f"{name} = {json.dumps(rows, indent=4, ensure_ascii=False)}\n"

    out = Path("farm_loop/pseo_data_devref.py")
    header = (
        '"""Vetted Git / regex / Linux reference datasets for pSEO clusters.\n'
        "Generated by scripts/gen_pseo_devref.py from a parallel-agent workflow and\n"
        'anchor-validated. Do not hand-edit; regenerate from the workflow output."""\n'
        "from __future__ import annotations\n\n"
    )
    out.write_text(
        header + dump("GIT_RECIPES", git) + "\n" + dump("REGEX_PATTERNS", regex) + "\n" + dump("LINUX_COMMANDS", linux),
        encoding="utf-8",
    )
    print(f"wrote {out}: {len(git)} git, {len(regex)} regex, {len(linux)} linux")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
