"""Generate farm_loop/pseo_data_iso.py from the ISO dataset workflow result.

Validates well-known anchors (Mexico MX/MEX/+52, MXN/USD/EUR currencies) before
emitting a clean Python data module the country/currency page builders consume.

Usage: python scripts/gen_pseo_iso.py <workflow_output.json>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def _load_result(path: str) -> dict:
    obj = json.loads(Path(path).read_text(encoding="utf-8"))
    return obj.get("result", obj)


def _check(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"validation failed: {message}")


def main() -> int:
    data = _load_result(sys.argv[1])
    countries = data["countries"]
    currencies = data["currencies"]

    _check(any(c["iso2"] == "MX" and c["iso3"] == "MEX" and c["dialing"] == "+52" for c in countries), "Mexico MX/MEX/+52")
    _check(any(c["iso2"] == "US" for c in countries), "United States present")
    _check(len(countries) >= 190, "at least 190 countries")
    _check(any(c["code"] == "MXN" for c in currencies), "MXN present")
    _check(any(c["code"] == "USD" for c in currencies), "USD present")
    _check(any(c["code"] == "EUR" for c in currencies), "EUR present")

    def dump(name: str, rows: list) -> str:
        return f"{name} = {json.dumps(rows, indent=4, ensure_ascii=False)}\n"

    out = Path("farm_loop/pseo_data_iso.py")
    header = (
        '"""Vetted ISO 3166 country and ISO 4217 currency datasets for pSEO clusters.\n'
        "Generated by scripts/gen_pseo_iso.py from a parallel-agent workflow and\n"
        'anchor-validated. Do not hand-edit; regenerate from the workflow output."""\n'
        "from __future__ import annotations\n\n"
    )
    out.write_text(header + dump("COUNTRIES", countries) + "\n" + dump("CURRENCIES", currencies), encoding="utf-8")
    print(f"wrote {out}: {len(countries)} countries, {len(currencies)} currencies")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
