"""Vetted reference datasets for pSEO clusters (HTTP status codes, MIME
types, HTTP headers, exit codes & signals). Generated by
scripts/gen_pseo_data.py from a parallel-agent workflow and anchor-validated.
Do not hand-edit; regenerate from the workflow output instead."""
from __future__ import annotations

HTTP_STATUS = [
    {
        "code": 100,
        "name": "Continue",
        "category": "1xx Informational",
        "description": "The client should continue with its request. The server has received the request headers and the client should proceed to send the request body, typically after sending an Expect: 100-continue header."
    },
    {
        "code": 101,
        "name": "Switching Protocols",
        "category": "1xx Informational",
        "description": "The server is switching to a different protocol as requested by the client via an Upgrade header. Returned, for example, when upgrading an HTTP connection to a WebSocket."
    },
    {
        "code": 102,
        "name": "Processing",
        "category": "1xx Informational",
        "description": "A WebDAV interim response indicating the server has accepted the request and is processing it but no response is yet available. Used to prevent the client from timing out on long operations."
    },
    {
        "code": 103,
        "name": "Early Hints",
        "category": "1xx Informational",
        "description": "Used to return some response header fields, such as Link, before the final response. Allows the client to begin preloading resources while the server prepares the final response."
    },
    {
        "code": 200,
        "name": "OK",
        "category": "2xx Success",
        "description": "The request succeeded. The meaning of success depends on the method: for GET the resource is in the body, for POST the result of the action is returned, and so on."
    },
    {
        "code": 201,
        "name": "Created",
        "category": "2xx Success",
        "description": "The request succeeded and a new resource was created as a result. This is typically the response sent after POST or PUT requests, often including a Location header for the new resource."
    },
    {
        "code": 202,
        "name": "Accepted",
        "category": "2xx Success",
        "description": "The request has been accepted for processing, but the processing has not been completed. The request may or may not eventually be acted upon, and is intended for asynchronous operations."
    },
    {
        "code": 203,
        "name": "Non-Authoritative Information",
        "category": "2xx Success",
        "description": "The returned metadata in the response headers is not the definitive set from the origin server but is gathered from a local or third-party copy, such as a transforming proxy."
    },
    {
        "code": 204,
        "name": "No Content",
        "category": "2xx Success",
        "description": "The server successfully processed the request and is not returning any content. The client may keep its current view, and any associated metadata may be updated via headers."
    },
    {
        "code": 205,
        "name": "Reset Content",
        "category": "2xx Success",
        "description": "The server successfully processed the request and instructs the client to reset the document view that sent the request, for example clearing a form for fresh input."
    },
    {
        "code": 206,
        "name": "Partial Content",
        "category": "2xx Success",
        "description": "The server is delivering only part of the resource due to a Range header sent by the client. Used for resumable downloads and splitting a download into multiple simultaneous streams."
    },
    {
        "code": 207,
        "name": "Multi-Status",
        "category": "2xx Success",
        "description": "A WebDAV response conveying information about multiple resources where multiple status codes may be appropriate. The body is an XML message containing separate status codes per operation."
    },
    {
        "code": 208,
        "name": "Already Reported",
        "category": "2xx Success",
        "description": "Used inside a WebDAV 207 Multi-Status response to avoid repeatedly enumerating the internal members of multiple bindings to the same collection that have already been reported."
    },
    {
        "code": 226,
        "name": "IM Used",
        "category": "2xx Success",
        "description": "The server has fulfilled a GET request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance (delta encoding)."
    },
    {
        "code": 300,
        "name": "Multiple Choices",
        "category": "3xx Redirection",
        "description": "The request has more than one possible response, each with its own representation. The user or user agent should choose one, often via a list of links provided in the response."
    },
    {
        "code": 301,
        "name": "Moved Permanently",
        "category": "3xx Redirection",
        "description": "The requested resource has been permanently moved to a new URL given by the Location header. Clients and search engines should update their links to the new URL."
    },
    {
        "code": 302,
        "name": "Found",
        "category": "3xx Redirection",
        "description": "The requested resource resides temporarily under a different URL given by the Location header. The client should continue to use the original URL for future requests."
    },
    {
        "code": 303,
        "name": "See Other",
        "category": "3xx Redirection",
        "description": "The response to the request can be found under another URL using a GET method. Commonly used to redirect after a POST so the result can be retrieved without resubmitting data."
    },
    {
        "code": 304,
        "name": "Not Modified",
        "category": "3xx Redirection",
        "description": "Used for conditional requests; indicates the resource has not been modified since the version specified by If-None-Match or If-Modified-Since headers. The client can use its cached copy."
    },
    {
        "code": 305,
        "name": "Use Proxy",
        "category": "3xx Redirection",
        "description": "The requested resource must be accessed through the proxy given by the Location header. Deprecated due to security concerns regarding in-band configuration of a proxy."
    },
    {
        "code": 306,
        "name": "(Unused)",
        "category": "3xx Redirection",
        "description": "This code is no longer used and is reserved. It was defined in a previous version of the HTTP specification under the name Switch Proxy but is now unused."
    },
    {
        "code": 307,
        "name": "Temporary Redirect",
        "category": "3xx Redirection",
        "description": "The requested resource resides temporarily under a different URL given by the Location header, and the client must use the same HTTP method as the original request when following the redirect."
    },
    {
        "code": 308,
        "name": "Permanent Redirect",
        "category": "3xx Redirection",
        "description": "The requested resource has been permanently moved to the URL given by the Location header, and the client must use the same HTTP method as the original request when following the redirect."
    },
    {
        "code": 400,
        "name": "Bad Request",
        "category": "4xx Client Error",
        "description": "The server cannot or will not process the request due to a client error, such as malformed request syntax, invalid request message framing, or deceptive request routing."
    },
    {
        "code": 401,
        "name": "Unauthorized",
        "category": "4xx Client Error",
        "description": "The request lacks valid authentication credentials for the target resource. The client must authenticate itself, and the response includes a WWW-Authenticate header describing how."
    },
    {
        "code": 402,
        "name": "Payment Required",
        "category": "4xx Client Error",
        "description": "Reserved for future use; originally intended for digital payment systems. It is rarely used and not standardized, though some services employ it to signal usage or quota limits."
    },
    {
        "code": 403,
        "name": "Forbidden",
        "category": "4xx Client Error",
        "description": "The server understood the request but refuses to authorize it. Unlike 401, re-authenticating will not help; access is permanently denied based on the client's identity or permissions."
    },
    {
        "code": 404,
        "name": "Not Found",
        "category": "4xx Client Error",
        "description": "The server cannot find the requested resource. This may mean the URL is not recognized, the resource does not exist, or the server is hiding its existence from an unauthorized client."
    },
    {
        "code": 405,
        "name": "Method Not Allowed",
        "category": "4xx Client Error",
        "description": "The request method is known by the server but is not supported by the target resource. The response must include an Allow header listing the methods the resource does support."
    },
    {
        "code": 406,
        "name": "Not Acceptable",
        "category": "4xx Client Error",
        "description": "The server cannot produce a response matching the list of acceptable values defined in the request's proactive content negotiation headers, such as Accept, Accept-Language, or Accept-Encoding."
    },
    {
        "code": 407,
        "name": "Proxy Authentication Required",
        "category": "4xx Client Error",
        "description": "Similar to 401, but authentication is needed to be performed by a proxy. The proxy must return a Proxy-Authenticate header containing the challenge applicable to the proxy."
    },
    {
        "code": 408,
        "name": "Request Timeout",
        "category": "4xx Client Error",
        "description": "The server did not receive a complete request message within the time it was prepared to wait. The server may close the connection, and the client may repeat the request later."
    },
    {
        "code": 409,
        "name": "Conflict",
        "category": "4xx Client Error",
        "description": "The request conflicts with the current state of the target resource. Often returned for version control conflicts, such as a PUT that would overwrite a newer change."
    },
    {
        "code": 410,
        "name": "Gone",
        "category": "4xx Client Error",
        "description": "The requested resource is no longer available at the server and no forwarding address is known. This condition is expected to be permanent, unlike a 404 Not Found."
    },
    {
        "code": 411,
        "name": "Length Required",
        "category": "4xx Client Error",
        "description": "The server refuses to accept the request without a defined Content-Length header. The client should add a valid Content-Length header indicating the size of the request body and retry."
    },
    {
        "code": 412,
        "name": "Precondition Failed",
        "category": "4xx Client Error",
        "description": "One or more conditions given in the request header fields, such as If-Unmodified-Since or If-Match, evaluated to false when tested on the server. The requested operation was not performed."
    },
    {
        "code": 413,
        "name": "Content Too Large",
        "category": "4xx Client Error",
        "description": "The request body is larger than the limits defined by the server. The server may close the connection or return a Retry-After header. Previously named Request Entity Too Large."
    },
    {
        "code": 414,
        "name": "URI Too Long",
        "category": "4xx Client Error",
        "description": "The URI requested by the client is longer than the server is willing to interpret. This may occur when too much data is encoded into a GET request's query string."
    },
    {
        "code": 415,
        "name": "Unsupported Media Type",
        "category": "4xx Client Error",
        "description": "The server refuses to accept the request because the payload's media type is in a format not supported by the target resource for the given method, per the Content-Type or Content-Encoding."
    },
    {
        "code": 416,
        "name": "Range Not Satisfiable",
        "category": "4xx Client Error",
        "description": "The range specified by the Range header field in the request cannot be fulfilled, for example because it lies outside the size of the target resource's data."
    },
    {
        "code": 417,
        "name": "Expectation Failed",
        "category": "4xx Client Error",
        "description": "The expectation indicated by the Expect request header field cannot be met by the server. This typically relates to an Expect: 100-continue header the server cannot satisfy."
    },
    {
        "code": 418,
        "name": "I'm a teapot",
        "category": "4xx Client Error",
        "description": "The server refuses to brew coffee because it is, permanently, a teapot. Defined as an April Fools' joke in RFC 2324 (Hyper Text Coffee Pot Control Protocol) and not a real HTTP status."
    },
    {
        "code": 421,
        "name": "Misdirected Request",
        "category": "4xx Client Error",
        "description": "The request was directed at a server that is not able to produce a response. Sent when a connection is reused for a request to an authority for which the server is not configured."
    },
    {
        "code": 422,
        "name": "Unprocessable Content",
        "category": "4xx Client Error",
        "description": "The server understands the content type and syntax of the request but was unable to process the contained instructions due to semantic errors. Originally a WebDAV code, now widely used by APIs."
    },
    {
        "code": 423,
        "name": "Locked",
        "category": "4xx Client Error",
        "description": "A WebDAV code indicating the source or destination resource of a method is locked. The response should contain information identifying the lock and the means to unlock it."
    },
    {
        "code": 424,
        "name": "Failed Dependency",
        "category": "4xx Client Error",
        "description": "A WebDAV code indicating the requested action depended on another action that failed, so the request could not be performed. Often seen within batched or multi-step operations."
    },
    {
        "code": 425,
        "name": "Too Early",
        "category": "4xx Client Error",
        "description": "The server is unwilling to risk processing a request that might be replayed, such as one sent within TLS 1.3 early data, to protect against replay attacks."
    },
    {
        "code": 426,
        "name": "Upgrade Required",
        "category": "4xx Client Error",
        "description": "The server refuses to perform the request using the current protocol but may do so after the client upgrades to a different protocol. The server sends an Upgrade header indicating required protocols."
    },
    {
        "code": 428,
        "name": "Precondition Required",
        "category": "4xx Client Error",
        "description": "The origin server requires the request to be conditional. Intended to prevent the lost update problem where a client overwrites changes made on the server using an unconditional request."
    },
    {
        "code": 429,
        "name": "Too Many Requests",
        "category": "4xx Client Error",
        "description": "The user has sent too many requests in a given amount of time (rate limiting). The response may include a Retry-After header indicating how long to wait before making a new request."
    },
    {
        "code": 431,
        "name": "Request Header Fields Too Large",
        "category": "4xx Client Error",
        "description": "The server is unwilling to process the request because its header fields are too large. The request may be resubmitted after reducing the size of the headers, individually or collectively."
    },
    {
        "code": 451,
        "name": "Unavailable For Legal Reasons",
        "category": "4xx Client Error",
        "description": "The server is denying access to the resource as a consequence of a legal demand, such as a government-mandated censorship or a takedown ordered by a court. The number references Fahrenheit 451."
    },
    {
        "code": 500,
        "name": "Internal Server Error",
        "category": "5xx Server Error",
        "description": "The server encountered an unexpected condition that prevented it from fulfilling the request. This generic error is returned when no more specific 5xx message is suitable."
    },
    {
        "code": 501,
        "name": "Not Implemented",
        "category": "5xx Server Error",
        "description": "The server does not support the functionality required to fulfill the request. This is the appropriate response when the server does not recognize the request method and cannot support it for any resource."
    },
    {
        "code": 502,
        "name": "Bad Gateway",
        "category": "5xx Server Error",
        "description": "The server, while acting as a gateway or proxy, received an invalid response from an inbound server it accessed while attempting to fulfill the request."
    },
    {
        "code": 503,
        "name": "Service Unavailable",
        "category": "5xx Server Error",
        "description": "The server is not ready to handle the request, commonly due to being overloaded or down for maintenance. A Retry-After header may indicate when to try again. This is usually a temporary condition."
    },
    {
        "code": 504,
        "name": "Gateway Timeout",
        "category": "5xx Server Error",
        "description": "The server, while acting as a gateway or proxy, did not receive a timely response from an upstream server it needed to access in order to complete the request."
    },
    {
        "code": 505,
        "name": "HTTP Version Not Supported",
        "category": "5xx Server Error",
        "description": "The server does not support, or refuses to support, the major version of HTTP that was used in the request message. The server should describe supported protocols in the response."
    },
    {
        "code": 506,
        "name": "Variant Also Negotiates",
        "category": "5xx Server Error",
        "description": "The server has an internal configuration error: the chosen variant resource is configured to engage in transparent content negotiation itself and is therefore not a proper endpoint in the negotiation process."
    },
    {
        "code": 507,
        "name": "Insufficient Storage",
        "category": "5xx Server Error",
        "description": "A WebDAV code indicating the method could not be performed on the resource because the server is unable to store the representation needed to successfully complete the request."
    },
    {
        "code": 508,
        "name": "Loop Detected",
        "category": "5xx Server Error",
        "description": "A WebDAV code indicating the server terminated an operation because it encountered an infinite loop while processing a request with Depth: infinity. The operation was aborted to avoid the loop."
    },
    {
        "code": 510,
        "name": "Not Extended",
        "category": "5xx Server Error",
        "description": "Further extensions to the request are required for the server to fulfill it. The policy for accessing the resource has not been met, per the HTTP Extension Framework defined in RFC 2774."
    },
    {
        "code": 511,
        "name": "Network Authentication Required",
        "category": "5xx Server Error",
        "description": "The client needs to authenticate to gain network access. Intended for use by intercepting proxies, such as captive portals on public Wi-Fi, to control access to the network."
    }
]

MIME_TYPES = [
    {
        "ext": "png",
        "mime": "image/png",
        "kind": "Image",
        "description": "Portable Network Graphics raster image with lossless compression."
    },
    {
        "ext": "jpg",
        "mime": "image/jpeg",
        "kind": "Image",
        "description": "JPEG lossy-compressed raster image."
    },
    {
        "ext": "jpeg",
        "mime": "image/jpeg",
        "kind": "Image",
        "description": "JPEG lossy-compressed raster image."
    },
    {
        "ext": "jfif",
        "mime": "image/jpeg",
        "kind": "Image",
        "description": "JPEG File Interchange Format image."
    },
    {
        "ext": "gif",
        "mime": "image/gif",
        "kind": "Image",
        "description": "Graphics Interchange Format image supporting animation."
    },
    {
        "ext": "webp",
        "mime": "image/webp",
        "kind": "Image",
        "description": "WebP modern raster image format by Google."
    },
    {
        "ext": "svg",
        "mime": "image/svg+xml",
        "kind": "Image",
        "description": "Scalable Vector Graphics XML-based vector image."
    },
    {
        "ext": "avif",
        "mime": "image/avif",
        "kind": "Image",
        "description": "AV1 Image File Format with high compression."
    },
    {
        "ext": "ico",
        "mime": "image/vnd.microsoft.icon",
        "kind": "Image",
        "description": "Windows icon image file."
    },
    {
        "ext": "bmp",
        "mime": "image/bmp",
        "kind": "Image",
        "description": "Bitmap uncompressed raster image."
    },
    {
        "ext": "tiff",
        "mime": "image/tiff",
        "kind": "Image",
        "description": "Tagged Image File Format raster image."
    },
    {
        "ext": "tif",
        "mime": "image/tiff",
        "kind": "Image",
        "description": "Tagged Image File Format raster image."
    },
    {
        "ext": "heic",
        "mime": "image/heic",
        "kind": "Image",
        "description": "High Efficiency Image Container photo format."
    },
    {
        "ext": "heif",
        "mime": "image/heif",
        "kind": "Image",
        "description": "High Efficiency Image File Format."
    },
    {
        "ext": "jxl",
        "mime": "image/jxl",
        "kind": "Image",
        "description": "JPEG XL next-generation image format."
    },
    {
        "ext": "apng",
        "mime": "image/apng",
        "kind": "Image",
        "description": "Animated Portable Network Graphics."
    },
    {
        "ext": "psd",
        "mime": "image/vnd.adobe.photoshop",
        "kind": "Image",
        "description": "Adobe Photoshop document image."
    },
    {
        "ext": "pdf",
        "mime": "application/pdf",
        "kind": "Document",
        "description": "Portable Document Format file."
    },
    {
        "ext": "doc",
        "mime": "application/msword",
        "kind": "Document",
        "description": "Legacy Microsoft Word document."
    },
    {
        "ext": "docx",
        "mime": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "kind": "Document",
        "description": "Microsoft Word Open XML document."
    },
    {
        "ext": "xls",
        "mime": "application/vnd.ms-excel",
        "kind": "Document",
        "description": "Legacy Microsoft Excel spreadsheet."
    },
    {
        "ext": "xlsx",
        "mime": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "kind": "Document",
        "description": "Microsoft Excel Open XML spreadsheet."
    },
    {
        "ext": "ppt",
        "mime": "application/vnd.ms-powerpoint",
        "kind": "Document",
        "description": "Legacy Microsoft PowerPoint presentation."
    },
    {
        "ext": "pptx",
        "mime": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "kind": "Document",
        "description": "Microsoft PowerPoint Open XML presentation."
    },
    {
        "ext": "odt",
        "mime": "application/vnd.oasis.opendocument.text",
        "kind": "Document",
        "description": "OpenDocument text document."
    },
    {
        "ext": "ods",
        "mime": "application/vnd.oasis.opendocument.spreadsheet",
        "kind": "Document",
        "description": "OpenDocument spreadsheet."
    },
    {
        "ext": "odp",
        "mime": "application/vnd.oasis.opendocument.presentation",
        "kind": "Document",
        "description": "OpenDocument presentation."
    },
    {
        "ext": "rtf",
        "mime": "application/rtf",
        "kind": "Document",
        "description": "Rich Text Format document."
    },
    {
        "ext": "txt",
        "mime": "text/plain",
        "kind": "Document",
        "description": "Plain text file."
    },
    {
        "ext": "csv",
        "mime": "text/csv",
        "kind": "Document",
        "description": "Comma-separated values tabular data."
    },
    {
        "ext": "tsv",
        "mime": "text/tab-separated-values",
        "kind": "Document",
        "description": "Tab-separated values tabular data."
    },
    {
        "ext": "md",
        "mime": "text/markdown",
        "kind": "Document",
        "description": "Markdown formatted text document."
    },
    {
        "ext": "markdown",
        "mime": "text/markdown",
        "kind": "Document",
        "description": "Markdown formatted text document."
    },
    {
        "ext": "tex",
        "mime": "application/x-tex",
        "kind": "Document",
        "description": "TeX typesetting source document."
    },
    {
        "ext": "pages",
        "mime": "application/vnd.apple.pages",
        "kind": "Document",
        "description": "Apple Pages word-processing document."
    },
    {
        "ext": "numbers",
        "mime": "application/vnd.apple.numbers",
        "kind": "Document",
        "description": "Apple Numbers spreadsheet."
    },
    {
        "ext": "key",
        "mime": "application/vnd.apple.keynote",
        "kind": "Document",
        "description": "Apple Keynote presentation."
    },
    {
        "ext": "html",
        "mime": "text/html",
        "kind": "Code",
        "description": "HyperText Markup Language web page."
    },
    {
        "ext": "htm",
        "mime": "text/html",
        "kind": "Code",
        "description": "HyperText Markup Language web page."
    },
    {
        "ext": "xhtml",
        "mime": "application/xhtml+xml",
        "kind": "Code",
        "description": "XHTML XML-serialized HTML document."
    },
    {
        "ext": "css",
        "mime": "text/css",
        "kind": "Code",
        "description": "Cascading Style Sheets stylesheet."
    },
    {
        "ext": "js",
        "mime": "text/javascript",
        "kind": "Code",
        "description": "JavaScript source script."
    },
    {
        "ext": "mjs",
        "mime": "text/javascript",
        "kind": "Code",
        "description": "JavaScript ES module source."
    },
    {
        "ext": "cjs",
        "mime": "text/javascript",
        "kind": "Code",
        "description": "CommonJS JavaScript module source."
    },
    {
        "ext": "json",
        "mime": "application/json",
        "kind": "Code",
        "description": "JavaScript Object Notation data."
    },
    {
        "ext": "jsonld",
        "mime": "application/ld+json",
        "kind": "Code",
        "description": "JSON for Linked Data."
    },
    {
        "ext": "ndjson",
        "mime": "application/x-ndjson",
        "kind": "Data",
        "description": "Newline-delimited JSON records."
    },
    {
        "ext": "xml",
        "mime": "application/xml",
        "kind": "Code",
        "description": "Extensible Markup Language document."
    },
    {
        "ext": "yaml",
        "mime": "application/yaml",
        "kind": "Code",
        "description": "YAML Ain't Markup Language data serialization."
    },
    {
        "ext": "yml",
        "mime": "application/yaml",
        "kind": "Code",
        "description": "YAML Ain't Markup Language data serialization."
    },
    {
        "ext": "toml",
        "mime": "application/toml",
        "kind": "Code",
        "description": "Tom's Obvious Minimal Language config."
    },
    {
        "ext": "ts",
        "mime": "text/typescript",
        "kind": "Code",
        "description": "TypeScript source file."
    },
    {
        "ext": "tsx",
        "mime": "text/typescript",
        "kind": "Code",
        "description": "TypeScript React JSX source file."
    },
    {
        "ext": "jsx",
        "mime": "text/jsx",
        "kind": "Code",
        "description": "JavaScript React JSX source file."
    },
    {
        "ext": "wasm",
        "mime": "application/wasm",
        "kind": "Code",
        "description": "WebAssembly binary module."
    },
    {
        "ext": "py",
        "mime": "text/x-python",
        "kind": "Code",
        "description": "Python source script."
    },
    {
        "ext": "rb",
        "mime": "text/x-ruby",
        "kind": "Code",
        "description": "Ruby source script."
    },
    {
        "ext": "php",
        "mime": "application/x-httpd-php",
        "kind": "Code",
        "description": "PHP server-side source script."
    },
    {
        "ext": "java",
        "mime": "text/x-java-source",
        "kind": "Code",
        "description": "Java source file."
    },
    {
        "ext": "c",
        "mime": "text/x-c",
        "kind": "Code",
        "description": "C language source file."
    },
    {
        "ext": "cpp",
        "mime": "text/x-c",
        "kind": "Code",
        "description": "C++ language source file."
    },
    {
        "ext": "h",
        "mime": "text/x-c",
        "kind": "Code",
        "description": "C/C++ header file."
    },
    {
        "ext": "go",
        "mime": "text/x-go",
        "kind": "Code",
        "description": "Go language source file."
    },
    {
        "ext": "rs",
        "mime": "text/x-rust",
        "kind": "Code",
        "description": "Rust language source file."
    },
    {
        "ext": "sh",
        "mime": "application/x-sh",
        "kind": "Code",
        "description": "Shell script."
    },
    {
        "ext": "ps1",
        "mime": "application/x-powershell",
        "kind": "Code",
        "description": "PowerShell script."
    },
    {
        "ext": "sql",
        "mime": "application/sql",
        "kind": "Data",
        "description": "SQL database query/schema script."
    },
    {
        "ext": "csh",
        "mime": "application/x-csh",
        "kind": "Code",
        "description": "C shell script."
    },
    {
        "ext": "map",
        "mime": "application/json",
        "kind": "Code",
        "description": "Source map JSON file."
    },
    {
        "ext": "ipynb",
        "mime": "application/x-ipynb+json",
        "kind": "Code",
        "description": "Jupyter notebook JSON document."
    },
    {
        "ext": "mp3",
        "mime": "audio/mpeg",
        "kind": "Audio",
        "description": "MPEG-1/2 Audio Layer III compressed audio."
    },
    {
        "ext": "wav",
        "mime": "audio/wav",
        "kind": "Audio",
        "description": "Waveform uncompressed audio."
    },
    {
        "ext": "ogg",
        "mime": "audio/ogg",
        "kind": "Audio",
        "description": "Ogg container audio."
    },
    {
        "ext": "oga",
        "mime": "audio/ogg",
        "kind": "Audio",
        "description": "Ogg Vorbis audio."
    },
    {
        "ext": "flac",
        "mime": "audio/flac",
        "kind": "Audio",
        "description": "Free Lossless Audio Codec audio."
    },
    {
        "ext": "aac",
        "mime": "audio/aac",
        "kind": "Audio",
        "description": "Advanced Audio Coding compressed audio."
    },
    {
        "ext": "m4a",
        "mime": "audio/mp4",
        "kind": "Audio",
        "description": "MPEG-4 container audio."
    },
    {
        "ext": "opus",
        "mime": "audio/opus",
        "kind": "Audio",
        "description": "Opus low-latency compressed audio."
    },
    {
        "ext": "weba",
        "mime": "audio/webm",
        "kind": "Audio",
        "description": "WebM container audio."
    },
    {
        "ext": "mid",
        "mime": "audio/midi",
        "kind": "Audio",
        "description": "Musical Instrument Digital Interface sequence."
    },
    {
        "ext": "midi",
        "mime": "audio/midi",
        "kind": "Audio",
        "description": "Musical Instrument Digital Interface sequence."
    },
    {
        "ext": "aiff",
        "mime": "audio/aiff",
        "kind": "Audio",
        "description": "Audio Interchange File Format audio."
    },
    {
        "ext": "wma",
        "mime": "audio/x-ms-wma",
        "kind": "Audio",
        "description": "Windows Media Audio file."
    },
    {
        "ext": "mp4",
        "mime": "video/mp4",
        "kind": "Video",
        "description": "MPEG-4 Part 14 container video."
    },
    {
        "ext": "m4v",
        "mime": "video/mp4",
        "kind": "Video",
        "description": "MPEG-4 video variant."
    },
    {
        "ext": "webm",
        "mime": "video/webm",
        "kind": "Video",
        "description": "WebM open container video."
    },
    {
        "ext": "mov",
        "mime": "video/quicktime",
        "kind": "Video",
        "description": "Apple QuickTime container video."
    },
    {
        "ext": "avi",
        "mime": "video/x-msvideo",
        "kind": "Video",
        "description": "Audio Video Interleave container."
    },
    {
        "ext": "mkv",
        "mime": "video/x-matroska",
        "kind": "Video",
        "description": "Matroska multimedia container video."
    },
    {
        "ext": "mpeg",
        "mime": "video/mpeg",
        "kind": "Video",
        "description": "MPEG-1/2 video stream."
    },
    {
        "ext": "mpg",
        "mime": "video/mpeg",
        "kind": "Video",
        "description": "MPEG-1/2 video stream."
    },
    {
        "ext": "wmv",
        "mime": "video/x-ms-wmv",
        "kind": "Video",
        "description": "Windows Media Video file."
    },
    {
        "ext": "flv",
        "mime": "video/x-flv",
        "kind": "Video",
        "description": "Flash Video container."
    },
    {
        "ext": "3gp",
        "mime": "video/3gpp",
        "kind": "Video",
        "description": "3GPP mobile multimedia container."
    },
    {
        "ext": "ts",
        "mime": "video/mp2t",
        "kind": "Video",
        "description": "MPEG-2 Transport Stream video."
    },
    {
        "ext": "ogv",
        "mime": "video/ogg",
        "kind": "Video",
        "description": "Ogg container video."
    },
    {
        "ext": "zip",
        "mime": "application/zip",
        "kind": "Archive",
        "description": "ZIP compressed archive."
    },
    {
        "ext": "gz",
        "mime": "application/gzip",
        "kind": "Archive",
        "description": "Gzip compressed file."
    },
    {
        "ext": "tar",
        "mime": "application/x-tar",
        "kind": "Archive",
        "description": "Tape archive bundle."
    },
    {
        "ext": "tgz",
        "mime": "application/gzip",
        "kind": "Archive",
        "description": "Gzip-compressed tar archive."
    },
    {
        "ext": "rar",
        "mime": "application/vnd.rar",
        "kind": "Archive",
        "description": "RAR compressed archive."
    },
    {
        "ext": "7z",
        "mime": "application/x-7z-compressed",
        "kind": "Archive",
        "description": "7-Zip compressed archive."
    },
    {
        "ext": "bz2",
        "mime": "application/x-bzip2",
        "kind": "Archive",
        "description": "Bzip2 compressed file."
    },
    {
        "ext": "xz",
        "mime": "application/x-xz",
        "kind": "Archive",
        "description": "XZ compressed file."
    },
    {
        "ext": "zst",
        "mime": "application/zstd",
        "kind": "Archive",
        "description": "Zstandard compressed file."
    },
    {
        "ext": "lz",
        "mime": "application/x-lzip",
        "kind": "Archive",
        "description": "Lzip compressed file."
    },
    {
        "ext": "z",
        "mime": "application/x-compress",
        "kind": "Archive",
        "description": "Unix compress (.Z) file."
    },
    {
        "ext": "cab",
        "mime": "application/vnd.ms-cab-compressed",
        "kind": "Archive",
        "description": "Microsoft Cabinet archive."
    },
    {
        "ext": "woff",
        "mime": "font/woff",
        "kind": "Font",
        "description": "Web Open Font Format file."
    },
    {
        "ext": "woff2",
        "mime": "font/woff2",
        "kind": "Font",
        "description": "Web Open Font Format 2 file."
    },
    {
        "ext": "ttf",
        "mime": "font/ttf",
        "kind": "Font",
        "description": "TrueType font file."
    },
    {
        "ext": "otf",
        "mime": "font/otf",
        "kind": "Font",
        "description": "OpenType font file."
    },
    {
        "ext": "eot",
        "mime": "application/vnd.ms-fontobject",
        "kind": "Font",
        "description": "Embedded OpenType font file."
    },
    {
        "ext": "sfnt",
        "mime": "font/sfnt",
        "kind": "Font",
        "description": "SFNT-based font container."
    },
    {
        "ext": "db",
        "mime": "application/vnd.sqlite3",
        "kind": "Data",
        "description": "Generic SQLite/database file."
    },
    {
        "ext": "sqlite",
        "mime": "application/vnd.sqlite3",
        "kind": "Data",
        "description": "SQLite database file."
    },
    {
        "ext": "sqlite3",
        "mime": "application/vnd.sqlite3",
        "kind": "Data",
        "description": "SQLite database file."
    },
    {
        "ext": "parquet",
        "mime": "application/vnd.apache.parquet",
        "kind": "Data",
        "description": "Apache Parquet columnar data file."
    },
    {
        "ext": "avro",
        "mime": "application/avro",
        "kind": "Data",
        "description": "Apache Avro serialized data file."
    },
    {
        "ext": "proto",
        "mime": "text/plain",
        "kind": "Data",
        "description": "Protocol Buffers schema definition."
    },
    {
        "ext": "ics",
        "mime": "text/calendar",
        "kind": "Data",
        "description": "iCalendar calendar data file."
    },
    {
        "ext": "vcf",
        "mime": "text/vcard",
        "kind": "Data",
        "description": "vCard contact data file."
    },
    {
        "ext": "epub",
        "mime": "application/epub+zip",
        "kind": "Document",
        "description": "EPUB electronic publication ebook."
    },
    {
        "ext": "mobi",
        "mime": "application/x-mobipocket-ebook",
        "kind": "Document",
        "description": "Mobipocket ebook file."
    },
    {
        "ext": "apk",
        "mime": "application/vnd.android.package-archive",
        "kind": "Archive",
        "description": "Android application package."
    },
    {
        "ext": "deb",
        "mime": "application/vnd.debian.binary-package",
        "kind": "Archive",
        "description": "Debian software package."
    },
    {
        "ext": "rpm",
        "mime": "application/x-rpm",
        "kind": "Archive",
        "description": "RPM Linux software package."
    },
    {
        "ext": "dmg",
        "mime": "application/x-apple-diskimage",
        "kind": "Archive",
        "description": "Apple macOS disk image."
    },
    {
        "ext": "exe",
        "mime": "application/vnd.microsoft.portable-executable",
        "kind": "Application",
        "description": "Windows portable executable program."
    },
    {
        "ext": "msi",
        "mime": "application/x-msdownload",
        "kind": "Application",
        "description": "Windows installer package."
    },
    {
        "ext": "iso",
        "mime": "application/x-iso9660-image",
        "kind": "Archive",
        "description": "ISO 9660 optical disc image."
    },
    {
        "ext": "bin",
        "mime": "application/octet-stream",
        "kind": "Data",
        "description": "Generic binary data file."
    },
    {
        "ext": "dll",
        "mime": "application/vnd.microsoft.portable-executable",
        "kind": "Application",
        "description": "Windows dynamic-link library."
    },
    {
        "ext": "jar",
        "mime": "application/java-archive",
        "kind": "Archive",
        "description": "Java archive package."
    },
    {
        "ext": "swf",
        "mime": "application/x-shockwave-flash",
        "kind": "Application",
        "description": "Adobe Shockwave Flash file."
    },
    {
        "ext": "webmanifest",
        "mime": "application/manifest+json",
        "kind": "Code",
        "description": "Web app manifest JSON file."
    },
    {
        "ext": "rss",
        "mime": "application/rss+xml",
        "kind": "Data",
        "description": "RSS web feed XML document."
    },
    {
        "ext": "atom",
        "mime": "application/atom+xml",
        "kind": "Data",
        "description": "Atom web feed XML document."
    },
    {
        "ext": "gpx",
        "mime": "application/gpx+xml",
        "kind": "Data",
        "description": "GPS Exchange Format XML data."
    },
    {
        "ext": "geojson",
        "mime": "application/geo+json",
        "kind": "Data",
        "description": "GeoJSON geospatial data."
    },
    {
        "ext": "p7s",
        "mime": "application/pkcs7-signature",
        "kind": "Data",
        "description": "PKCS#7 cryptographic signature."
    },
    {
        "ext": "pem",
        "mime": "application/x-pem-file",
        "kind": "Data",
        "description": "PEM-encoded cryptographic key/certificate."
    },
    {
        "ext": "crt",
        "mime": "application/x-x509-ca-cert",
        "kind": "Data",
        "description": "X.509 certificate file."
    }
]

HTTP_HEADERS = [
    {
        "name": "Accept",
        "direction": "Request",
        "description": "Tells the server which media (MIME) types the client can understand and prefer for the response, with optional quality weights.",
        "example": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,*/*;q=0.8"
    },
    {
        "name": "Accept-Charset",
        "direction": "Request",
        "description": "Indicates which character encodings the client can process in the response. Largely deprecated in favor of UTF-8 defaults.",
        "example": "utf-8, iso-8859-1;q=0.5"
    },
    {
        "name": "Accept-Encoding",
        "direction": "Request",
        "description": "Lists the content (compression) encodings the client supports, so the server can compress the response body.",
        "example": "gzip, deflate, br, zstd"
    },
    {
        "name": "Accept-Language",
        "direction": "Request",
        "description": "Communicates the natural languages the client prefers for the response, with optional quality values for ranking.",
        "example": "en-US,en;q=0.9,es;q=0.8"
    },
    {
        "name": "Accept-Ranges",
        "direction": "Response",
        "description": "Advertises whether the server supports range requests for a resource and in what unit (usually bytes).",
        "example": "bytes"
    },
    {
        "name": "Access-Control-Allow-Credentials",
        "direction": "Response",
        "description": "Tells the browser whether the response to a credentialed CORS request (cookies, TLS client certs, auth) may be exposed to the page.",
        "example": "true"
    },
    {
        "name": "Access-Control-Allow-Headers",
        "direction": "Response",
        "description": "Lists the request headers that are permitted during the actual CORS request; sent in response to a preflight request.",
        "example": "Content-Type, Authorization, X-Requested-With"
    },
    {
        "name": "Access-Control-Allow-Methods",
        "direction": "Response",
        "description": "Specifies the HTTP methods allowed when accessing the resource in a CORS request; returned in a preflight response.",
        "example": "GET, POST, PUT, DELETE, OPTIONS"
    },
    {
        "name": "Access-Control-Allow-Origin",
        "direction": "Response",
        "description": "Indicates which origin(s) are allowed to read the response in a cross-origin request, or '*' for any origin.",
        "example": "https://app.example.com"
    },
    {
        "name": "Access-Control-Expose-Headers",
        "direction": "Response",
        "description": "Lists the response headers (beyond the CORS-safelisted set) that JavaScript in the browser is allowed to access.",
        "example": "X-Request-Id, ETag, Content-Length"
    },
    {
        "name": "Access-Control-Max-Age",
        "direction": "Response",
        "description": "Specifies, in seconds, how long the results of a CORS preflight request can be cached by the browser.",
        "example": "86400"
    },
    {
        "name": "Access-Control-Request-Headers",
        "direction": "Request",
        "description": "Sent by the browser in a CORS preflight to tell the server which headers the actual request will include.",
        "example": "Content-Type, Authorization"
    },
    {
        "name": "Access-Control-Request-Method",
        "direction": "Request",
        "description": "Sent by the browser in a CORS preflight to tell the server which HTTP method the actual request will use.",
        "example": "POST"
    },
    {
        "name": "Age",
        "direction": "Response",
        "description": "Indicates the time in seconds the object has been in a proxy or CDN cache since it was generated or revalidated at the origin.",
        "example": "3600"
    },
    {
        "name": "Allow",
        "direction": "Response",
        "description": "Lists the set of HTTP methods supported by the target resource; commonly returned with a 405 Method Not Allowed response.",
        "example": "GET, HEAD, POST, OPTIONS"
    },
    {
        "name": "Authorization",
        "direction": "Request",
        "description": "Carries credentials to authenticate the client with the server, typically a scheme followed by a token or encoded value.",
        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
    },
    {
        "name": "Cache-Control",
        "direction": "Both",
        "description": "Directs caching behavior for both requests and responses, controlling freshness, storage, and revalidation rules.",
        "example": "public, max-age=3600, must-revalidate"
    },
    {
        "name": "Connection",
        "direction": "Both",
        "description": "Controls whether the network connection stays open after the current transaction and lists hop-by-hop headers. An HTTP/1.1 hop-by-hop header.",
        "example": "keep-alive"
    },
    {
        "name": "Content-Disposition",
        "direction": "Response",
        "description": "Signals whether the content should be displayed inline in the browser or treated as a downloadable attachment, optionally with a filename.",
        "example": "attachment; filename=\"report-2026.pdf\""
    },
    {
        "name": "Content-Encoding",
        "direction": "Response",
        "description": "Indicates the compression or encoding applied to the response body, which the client must reverse to obtain the original payload.",
        "example": "gzip"
    },
    {
        "name": "Content-Language",
        "direction": "Response",
        "description": "Describes the natural language(s) of the intended audience for the enclosed content.",
        "example": "en-US"
    },
    {
        "name": "Content-Length",
        "direction": "Both",
        "description": "Indicates the size of the message body in bytes (octets) sent to the recipient.",
        "example": "34829"
    },
    {
        "name": "Content-Location",
        "direction": "Response",
        "description": "Gives an alternate direct URL for the returned data, indicating where the specific representation can be accessed.",
        "example": "/documents/report.pdf"
    },
    {
        "name": "Content-Range",
        "direction": "Response",
        "description": "Indicates where a partial message body belongs within the full resource, returned in a 206 Partial Content response.",
        "example": "bytes 0-1023/146515"
    },
    {
        "name": "Content-Security-Policy",
        "direction": "Response",
        "description": "Defines an allowlist of content sources to mitigate cross-site scripting (XSS), clickjacking, and other injection attacks.",
        "example": "default-src 'self'; img-src 'self' data:; script-src 'self'"
    },
    {
        "name": "Content-Type",
        "direction": "Both",
        "description": "Declares the media type (and optional charset/boundary) of the message body so the recipient can parse it correctly.",
        "example": "application/json; charset=utf-8"
    },
    {
        "name": "Cookie",
        "direction": "Request",
        "description": "Sends stored HTTP cookies previously set by the server back to it, used for session state and personalization.",
        "example": "session_id=abc123; theme=dark; consent=true"
    },
    {
        "name": "Cross-Origin-Embedder-Policy",
        "direction": "Response",
        "description": "Controls whether a document can load cross-origin resources that don't explicitly grant permission, enabling cross-origin isolation.",
        "example": "require-corp"
    },
    {
        "name": "Cross-Origin-Opener-Policy",
        "direction": "Response",
        "description": "Controls whether a top-level document shares a browsing context group with cross-origin openers, helping isolate the page.",
        "example": "same-origin"
    },
    {
        "name": "Cross-Origin-Resource-Policy",
        "direction": "Response",
        "description": "Lets a server declare that a resource may only be loaded by documents from the same origin, same site, or any origin.",
        "example": "same-site"
    },
    {
        "name": "Date",
        "direction": "Both",
        "description": "Contains the date and time at which the message was originated, in HTTP-date format (RFC 7231).",
        "example": "Sat, 13 Jun 2026 18:24:00 GMT"
    },
    {
        "name": "ETag",
        "direction": "Response",
        "description": "Provides an opaque validator (entity tag) identifying a specific version of a resource, used for efficient cache revalidation.",
        "example": "\"33a64df551425fcc55e4d42a148795d9f25f89d4\""
    },
    {
        "name": "Expect",
        "direction": "Request",
        "description": "Indicates expectations the server must meet to handle the request, most commonly used for '100-continue' before sending a large body.",
        "example": "100-continue"
    },
    {
        "name": "Expires",
        "direction": "Response",
        "description": "Gives the date/time after which the response is considered stale; ignored if Cache-Control max-age is also present.",
        "example": "Sun, 14 Jun 2026 18:24:00 GMT"
    },
    {
        "name": "Forwarded",
        "direction": "Request",
        "description": "Standardized header (RFC 7239) that discloses client and proxy info altered or lost when requests pass through proxies.",
        "example": "for=192.0.2.60;proto=https;by=203.0.113.43"
    },
    {
        "name": "Host",
        "direction": "Request",
        "description": "Specifies the domain name and optional port of the server being requested; mandatory in HTTP/1.1.",
        "example": "www.example.com"
    },
    {
        "name": "If-Match",
        "direction": "Request",
        "description": "Makes the request conditional: the server applies it only if the resource's current ETag matches one listed, used to prevent lost updates.",
        "example": "\"33a64df551425fcc55e4d42a148795d9f25f89d4\""
    },
    {
        "name": "If-Modified-Since",
        "direction": "Request",
        "description": "Makes a GET conditional, asking the server to return the resource only if it has changed since the given date.",
        "example": "Sat, 13 Jun 2026 10:00:00 GMT"
    },
    {
        "name": "If-None-Match",
        "direction": "Request",
        "description": "Makes the request conditional on the resource's ETag not matching; returns 304 Not Modified if it still matches.",
        "example": "\"33a64df551425fcc55e4d42a148795d9f25f89d4\""
    },
    {
        "name": "If-Range",
        "direction": "Request",
        "description": "Used with Range to fetch missing bytes only if the resource is unchanged (matching ETag/date), otherwise the full resource is returned.",
        "example": "\"33a64df551425fcc55e4d42a148795d9f25f89d4\""
    },
    {
        "name": "If-Unmodified-Since",
        "direction": "Request",
        "description": "Makes the request conditional: the server proceeds only if the resource has not been modified since the given date.",
        "example": "Sat, 13 Jun 2026 10:00:00 GMT"
    },
    {
        "name": "Keep-Alive",
        "direction": "Both",
        "description": "Conveys parameters for a persistent connection, such as idle timeout and the maximum number of requests allowed.",
        "example": "timeout=5, max=1000"
    },
    {
        "name": "Last-Modified",
        "direction": "Response",
        "description": "Indicates the date and time at which the origin server believes the resource was last changed, used as a weak cache validator.",
        "example": "Fri, 12 Jun 2026 09:15:00 GMT"
    },
    {
        "name": "Link",
        "direction": "Response",
        "description": "Serializes one or more relationships between the resource and other URLs in HTTP headers, used for preload, pagination, and more.",
        "example": "<https://api.example.com/page/2>; rel=\"next\""
    },
    {
        "name": "Location",
        "direction": "Response",
        "description": "Indicates the URL to redirect to (with 3xx responses) or the URL of a newly created resource (with 201 Created).",
        "example": "https://www.example.com/new-page"
    },
    {
        "name": "Max-Forwards",
        "direction": "Request",
        "description": "Limits the number of times a TRACE or OPTIONS request can be forwarded by proxies, acting like a hop counter.",
        "example": "10"
    },
    {
        "name": "Origin",
        "direction": "Request",
        "description": "Indicates the origin (scheme, host, port) that initiated the request, used by servers in CORS and CSRF protection decisions.",
        "example": "https://app.example.com"
    },
    {
        "name": "Permissions-Policy",
        "direction": "Response",
        "description": "Allows a site to control which browser features and APIs (camera, geolocation, microphone, etc.) can be used in the document and its iframes.",
        "example": "geolocation=(self), camera=(), microphone=()"
    },
    {
        "name": "Pragma",
        "direction": "Both",
        "description": "Legacy HTTP/1.0 caching directive, retained mainly as 'no-cache' for backward compatibility with older proxies.",
        "example": "no-cache"
    },
    {
        "name": "Proxy-Authenticate",
        "direction": "Response",
        "description": "Sent with a 407 response to define the authentication method the client must use to access the resource through a proxy.",
        "example": "Basic realm=\"Proxy\""
    },
    {
        "name": "Proxy-Authorization",
        "direction": "Request",
        "description": "Carries credentials for the client to authenticate itself with a proxy that requires authentication.",
        "example": "Basic dXNlcjpwYXNzd29yZA=="
    },
    {
        "name": "Range",
        "direction": "Request",
        "description": "Requests only part of a resource by specifying one or more byte ranges, enabling resumable downloads and media seeking.",
        "example": "bytes=0-1023"
    },
    {
        "name": "Referer",
        "direction": "Request",
        "description": "Identifies the address of the previous web page from which a link to the currently requested resource was followed.",
        "example": "https://www.example.com/search?q=widgets"
    },
    {
        "name": "Referrer-Policy",
        "direction": "Response",
        "description": "Governs how much referrer information the browser includes in the Referer header for requests originating from the page.",
        "example": "strict-origin-when-cross-origin"
    },
    {
        "name": "Retry-After",
        "direction": "Response",
        "description": "Indicates how long the client should wait before retrying, sent with 503 (unavailable) or 429 (rate limited) responses.",
        "example": "120"
    },
    {
        "name": "Server",
        "direction": "Response",
        "description": "Describes the software and optionally version used by the origin server that handled the request.",
        "example": "nginx/1.25.3"
    },
    {
        "name": "Set-Cookie",
        "direction": "Response",
        "description": "Instructs the client to store a cookie with the given name, value, and attributes such as expiry, path, and security flags.",
        "example": "session_id=abc123; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=3600"
    },
    {
        "name": "Strict-Transport-Security",
        "direction": "Response",
        "description": "Tells browsers to access the site only over HTTPS for a specified duration, preventing protocol downgrade and SSL-stripping attacks.",
        "example": "max-age=31536000; includeSubDomains; preload"
    },
    {
        "name": "TE",
        "direction": "Request",
        "description": "Specifies the transfer encodings the client is willing to accept in the response, such as 'trailers' or 'gzip'. A hop-by-hop header.",
        "example": "trailers, deflate;q=0.5"
    },
    {
        "name": "Trailer",
        "direction": "Both",
        "description": "Lists the header fields that will be sent in the trailer section after a chunked-transfer-encoded message body.",
        "example": "Expires, Content-MD5"
    },
    {
        "name": "Transfer-Encoding",
        "direction": "Both",
        "description": "Specifies the form of encoding used to safely transfer the body, most commonly 'chunked'. A hop-by-hop header.",
        "example": "chunked"
    },
    {
        "name": "Upgrade",
        "direction": "Both",
        "description": "Asks the server to switch to a different protocol on the current connection, such as upgrading HTTP to WebSocket.",
        "example": "websocket"
    },
    {
        "name": "Upgrade-Insecure-Requests",
        "direction": "Request",
        "description": "Signals the client's preference to receive an encrypted, authenticated response and that it can handle upgrade of insecure HTTP resources to HTTPS.",
        "example": "1"
    },
    {
        "name": "User-Agent",
        "direction": "Request",
        "description": "Identifies the client software (browser, library, or bot) making the request, including product and platform details.",
        "example": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    },
    {
        "name": "Vary",
        "direction": "Response",
        "description": "Tells caches which request headers were used in content negotiation, so they can serve the correct cached variant.",
        "example": "Accept-Encoding, User-Agent"
    },
    {
        "name": "Via",
        "direction": "Both",
        "description": "Added by proxies and gateways to track message forwarding, identify protocol capabilities, and detect request loops.",
        "example": "1.1 vegur, 1.1 varnish"
    },
    {
        "name": "WWW-Authenticate",
        "direction": "Response",
        "description": "Sent with a 401 Unauthorized response to define the authentication scheme(s) and realm the client must use to gain access.",
        "example": "Bearer realm=\"api\", error=\"invalid_token\""
    },
    {
        "name": "X-Content-Type-Options",
        "direction": "Response",
        "description": "Disables browser MIME-type sniffing, forcing it to honor the declared Content-Type and reducing drive-by download risks.",
        "example": "nosniff"
    },
    {
        "name": "X-Forwarded-For",
        "direction": "Request",
        "description": "De facto standard added by proxies/load balancers to record the originating client IP and the chain of intermediary IPs.",
        "example": "203.0.113.195, 70.41.3.18, 150.172.238.178"
    },
    {
        "name": "X-Forwarded-Host",
        "direction": "Request",
        "description": "Identifies the original Host header requested by the client before it was changed by a reverse proxy or load balancer.",
        "example": "www.example.com"
    },
    {
        "name": "X-Forwarded-Proto",
        "direction": "Request",
        "description": "Conveys the protocol (http or https) the client used to connect to a proxy, helping the origin reconstruct the original scheme.",
        "example": "https"
    },
    {
        "name": "X-Frame-Options",
        "direction": "Response",
        "description": "Controls whether a page may be rendered in a frame, iframe, embed, or object, providing clickjacking protection.",
        "example": "DENY"
    },
    {
        "name": "X-Request-ID",
        "direction": "Both",
        "description": "Carries a unique identifier for a request to correlate logs across services for tracing and debugging.",
        "example": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
    },
    {
        "name": "X-XSS-Protection",
        "direction": "Response",
        "description": "Legacy header that controlled the browser's built-in reflected-XSS filter; deprecated in modern browsers in favor of CSP.",
        "example": "1; mode=block"
    }
]

EXIT_SIGNALS = [
    {
        "number": 0,
        "label": "Success",
        "kind": "exit",
        "description": "The command completed successfully without errors. By convention, zero indicates success for all Unix programs."
    },
    {
        "number": 1,
        "label": "General error",
        "kind": "exit",
        "description": "Catch-all for general errors. Used when a command fails but no more specific exit code applies, such as a division by zero or a generic failed operation."
    },
    {
        "number": 2,
        "label": "Misuse of shell builtin",
        "kind": "exit",
        "description": "Incorrect usage of a shell builtin, such as a missing keyword, an invalid option, or a syntax error in arguments. Bash also returns 2 for usage errors."
    },
    {
        "number": 126,
        "label": "Command not executable",
        "kind": "exit",
        "description": "The command was found but could not be executed, typically due to insufficient permissions (not marked executable) or because the target is a directory."
    },
    {
        "number": 127,
        "label": "Command not found",
        "kind": "exit",
        "description": "The shell could not find the command. Usually caused by a typo in the command name or a missing entry in $PATH."
    },
    {
        "number": 128,
        "label": "Invalid exit argument",
        "kind": "exit",
        "description": "An invalid argument was passed to the exit builtin (e.g. a non-integer or out-of-range value). Also the base offset to which a signal number is added for signal-terminated processes."
    },
    {
        "number": 130,
        "label": "Terminated by Ctrl-C (SIGINT)",
        "kind": "exit",
        "description": "The process was terminated by SIGINT, usually from pressing Ctrl-C at the keyboard. Computed as 128 + 2 (SIGINT)."
    },
    {
        "number": 131,
        "label": "Terminated by SIGQUIT",
        "kind": "exit",
        "description": "The process was terminated by SIGQUIT, typically from pressing Ctrl-backslash, which also dumps core. Computed as 128 + 3 (SIGQUIT)."
    },
    {
        "number": 132,
        "label": "Illegal instruction (SIGILL)",
        "kind": "exit",
        "description": "The process was terminated by SIGILL after attempting an illegal CPU instruction. Computed as 128 + 4 (SIGILL)."
    },
    {
        "number": 134,
        "label": "Aborted (SIGABRT)",
        "kind": "exit",
        "description": "The process called abort(), often via an assertion failure or detected corruption, and was terminated by SIGABRT. Computed as 128 + 6 (SIGABRT)."
    },
    {
        "number": 136,
        "label": "Floating-point exception (SIGFPE)",
        "kind": "exit",
        "description": "The process was terminated by SIGFPE, commonly from integer division by zero or overflow. Computed as 128 + 8 (SIGFPE)."
    },
    {
        "number": 137,
        "label": "Killed (SIGKILL / OOM)",
        "kind": "exit",
        "description": "The process received SIGKILL and was forcibly terminated, often by the out-of-memory killer or an explicit kill -9. Computed as 128 + 9 (SIGKILL)."
    },
    {
        "number": 139,
        "label": "Segmentation fault (SIGSEGV)",
        "kind": "exit",
        "description": "The process crashed with a segmentation fault from an invalid memory access. Computed as 128 + 11 (SIGSEGV)."
    },
    {
        "number": 141,
        "label": "Broken pipe (SIGPIPE)",
        "kind": "exit",
        "description": "The process was terminated by SIGPIPE after writing to a pipe whose read end was closed. Computed as 128 + 13 (SIGPIPE)."
    },
    {
        "number": 143,
        "label": "Terminated (SIGTERM)",
        "kind": "exit",
        "description": "The process was terminated by SIGTERM, the default graceful-shutdown signal sent by kill and by process managers. Computed as 128 + 15 (SIGTERM)."
    },
    {
        "number": 255,
        "label": "Exit status out of range",
        "kind": "exit",
        "description": "An exit code outside the valid 0-255 range was used (e.g. exit -1 or exit 256), which wraps around. Also commonly returned by programs like SSH on fatal errors."
    },
    {
        "number": 1,
        "label": "SIGHUP",
        "kind": "signal",
        "description": "Hangup detected on the controlling terminal or death of the controlling process. Often repurposed to tell daemons to reload their configuration."
    },
    {
        "number": 2,
        "label": "SIGINT",
        "kind": "signal",
        "description": "Interrupt from the keyboard, typically generated by pressing Ctrl-C. Requests the process to terminate and can be caught or ignored."
    },
    {
        "number": 3,
        "label": "SIGQUIT",
        "kind": "signal",
        "description": "Quit from the keyboard, typically Ctrl-backslash. Like SIGINT but also produces a core dump for debugging."
    },
    {
        "number": 4,
        "label": "SIGILL",
        "kind": "signal",
        "description": "Illegal instruction. The CPU attempted to execute a malformed or privileged machine instruction, usually indicating a corrupted binary or program bug."
    },
    {
        "number": 5,
        "label": "SIGTRAP",
        "kind": "signal",
        "description": "Trace or breakpoint trap. Used by debuggers to implement breakpoints and single-stepping; raised when a trap instruction executes."
    },
    {
        "number": 6,
        "label": "SIGABRT",
        "kind": "signal",
        "description": "Abort signal, raised by the abort() function. Commonly triggered by assertion failures or detected internal corruption; produces a core dump."
    },
    {
        "number": 7,
        "label": "SIGBUS",
        "kind": "signal",
        "description": "Bus error from an unaligned memory access or accessing a memory-mapped region that is no longer valid. Distinct from SIGSEGV in cause."
    },
    {
        "number": 8,
        "label": "SIGFPE",
        "kind": "signal",
        "description": "Floating-point exception, despite the name often caused by integer division by zero or integer overflow as well as erroneous floating-point operations."
    },
    {
        "number": 9,
        "label": "SIGKILL",
        "kind": "signal",
        "description": "Kill signal that forcibly and immediately terminates the process. Cannot be caught, blocked, or ignored, making it the last resort to stop a process."
    },
    {
        "number": 10,
        "label": "SIGUSR1",
        "kind": "signal",
        "description": "User-defined signal 1. Has no preset meaning and is reserved for application-specific use, often to trigger custom behavior like log rotation."
    },
    {
        "number": 11,
        "label": "SIGSEGV",
        "kind": "signal",
        "description": "Segmentation violation. The process referenced memory it is not allowed to access, such as dereferencing a null or dangling pointer; produces a core dump."
    },
    {
        "number": 12,
        "label": "SIGUSR2",
        "kind": "signal",
        "description": "User-defined signal 2. A second application-defined signal with no preset meaning, available for custom inter-process communication."
    },
    {
        "number": 13,
        "label": "SIGPIPE",
        "kind": "signal",
        "description": "Broken pipe. The process wrote to a pipe or socket whose reading end has been closed, e.g. when a downstream command in a pipeline exits early."
    },
    {
        "number": 14,
        "label": "SIGALRM",
        "kind": "signal",
        "description": "Alarm clock. Sent when a timer set with alarm() or setitimer() expires, commonly used to implement timeouts."
    },
    {
        "number": 15,
        "label": "SIGTERM",
        "kind": "signal",
        "description": "Termination request. The default and polite way to ask a process to shut down; it can be caught to perform cleanup before exiting."
    },
    {
        "number": 17,
        "label": "SIGCHLD",
        "kind": "signal",
        "description": "Child status changed. Sent to a parent process when a child terminates, stops, or resumes, allowing the parent to reap it with wait()."
    },
    {
        "number": 18,
        "label": "SIGCONT",
        "kind": "signal",
        "description": "Continue if stopped. Resumes a process that was previously paused by SIGSTOP or SIGTSTP, used for job control."
    },
    {
        "number": 19,
        "label": "SIGSTOP",
        "kind": "signal",
        "description": "Stop the process. Unconditionally pauses execution and cannot be caught, blocked, or ignored; the process resumes only on SIGCONT."
    },
    {
        "number": 20,
        "label": "SIGTSTP",
        "kind": "signal",
        "description": "Terminal stop request, typically generated by pressing Ctrl-Z. Suspends the process but, unlike SIGSTOP, can be caught or ignored."
    },
    {
        "number": 21,
        "label": "SIGTTIN",
        "kind": "signal",
        "description": "Background process attempted to read from the controlling terminal. The kernel stops the process until it is brought to the foreground."
    },
    {
        "number": 22,
        "label": "SIGTTOU",
        "kind": "signal",
        "description": "Background process attempted to write to the controlling terminal (when stty tostop is set). The kernel stops the process until foregrounded."
    },
    {
        "number": 24,
        "label": "SIGXCPU",
        "kind": "signal",
        "description": "CPU time limit exceeded. Sent when the process exceeds its soft RLIMIT_CPU limit, giving it a chance to clean up before SIGKILL follows."
    },
    {
        "number": 25,
        "label": "SIGXFSZ",
        "kind": "signal",
        "description": "File size limit exceeded. Sent when the process tries to grow a file beyond the RLIMIT_FSIZE soft limit."
    },
    {
        "number": 26,
        "label": "SIGVTALRM",
        "kind": "signal",
        "description": "Virtual alarm clock. Sent when a virtual (process user-time) timer set with setitimer(ITIMER_VIRTUAL) expires."
    },
    {
        "number": 28,
        "label": "SIGWINCH",
        "kind": "signal",
        "description": "Window size change. Sent to processes when the controlling terminal's window dimensions change, letting them re-layout their output."
    }
]
