"""Vetted Git / regex / Linux reference datasets for pSEO clusters.
Generated by scripts/gen_pseo_devref.py from a parallel-agent workflow and
anchor-validated. Do not hand-edit; regenerate from the workflow output."""
from __future__ import annotations

GIT_RECIPES = [
    {
        "task": "Undo the last commit but keep the changes staged",
        "command": "git reset --soft HEAD~1",
        "explanation": "Moves HEAD back one commit while leaving all changes staged in the index. Safe — nothing is lost; you can re-commit immediately."
    },
    {
        "task": "Undo the last commit and keep changes unstaged",
        "command": "git reset --mixed HEAD~1   (or just: git reset HEAD~1)",
        "explanation": "Rolls back the last commit and unstages the changes, but keeps them in your working directory. Safe; --mixed is the default mode."
    },
    {
        "task": "Undo the last commit AND throw away the changes",
        "command": "git reset --hard HEAD~1",
        "explanation": "Deletes the last commit and all its changes from the working tree. DANGER: uncommitted work is gone permanently — only use if you truly want to discard everything."
    },
    {
        "task": "Discard all local uncommitted changes",
        "command": "git reset --hard HEAD",
        "explanation": "Resets tracked files back to the last commit, wiping every uncommitted modification. DANGER: irreversible for unsaved work; untracked files are NOT removed."
    },
    {
        "task": "Discard changes to a single file",
        "command": "git restore <file>   (older Git: git checkout -- <file>)",
        "explanation": "Reverts one file to its last committed state. DANGER: your local edits to that file are lost and unrecoverable."
    },
    {
        "task": "Remove untracked files and directories",
        "command": "git clean -fd   (preview first: git clean -nd)",
        "explanation": "Deletes files/folders Git isn't tracking. DANGER: permanent. Always run with -n (dry run) first to see what will be deleted."
    },
    {
        "task": "Unstage a file (keep the edits)",
        "command": "git restore --staged <file>   (older Git: git reset HEAD <file>)",
        "explanation": "Removes a file from the staging area but keeps your changes in the working directory. Completely safe."
    },
    {
        "task": "Unstage everything",
        "command": "git reset",
        "explanation": "Clears the staging area while leaving all working-directory changes intact. Safe — nothing is committed or deleted."
    },
    {
        "task": "Amend the last commit message",
        "command": "git commit --amend -m \"new message\"",
        "explanation": "Rewrites the most recent commit's message. DANGER if already pushed — it rewrites history and you'll need a force push, disrupting collaborators."
    },
    {
        "task": "Add forgotten files to the last commit",
        "command": "git add <file> && git commit --amend --no-edit",
        "explanation": "Folds newly staged changes into the previous commit without changing its message. DANGER if pushed — rewrites history."
    },
    {
        "task": "Create and switch to a new branch",
        "command": "git switch -c <branch>   (older Git: git checkout -b <branch>)",
        "explanation": "Creates a new branch from your current commit and checks it out in one step. Safe."
    },
    {
        "task": "Switch to an existing branch",
        "command": "git switch <branch>   (older Git: git checkout <branch>)",
        "explanation": "Moves you to another existing branch. Safe; Git warns if you have conflicting uncommitted changes."
    },
    {
        "task": "Delete a local branch",
        "command": "git branch -d <branch>   (force: git branch -D <branch>)",
        "explanation": "Removes a local branch. -d refuses if it has unmerged commits; -D forces deletion. DANGER with -D — unmerged commits may become unreachable."
    },
    {
        "task": "Delete a remote branch",
        "command": "git push origin --delete <branch>",
        "explanation": "Deletes the branch on the remote (e.g. GitHub). DANGER: affects everyone using that remote; coordinate before deleting shared branches."
    },
    {
        "task": "Rename the current branch",
        "command": "git branch -m <new-name>",
        "explanation": "Renames the branch you're on. Safe locally; if it was already pushed you must push the new name and delete the old remote branch."
    },
    {
        "task": "Rename a remote branch",
        "command": "git branch -m old new && git push origin new && git push origin --delete old",
        "explanation": "Renames locally, pushes the new name, then deletes the old one on the remote. DANGER: collaborators must re-track; coordinate first."
    },
    {
        "task": "Rename a branch you're not currently on",
        "command": "git branch -m <old-name> <new-name>",
        "explanation": "Renames another local branch without checking it out. Safe locally."
    },
    {
        "task": "Undo a commit that's already been pushed",
        "command": "git revert <commit-hash>",
        "explanation": "Creates a NEW commit that reverses the target commit's changes, preserving history. Safe for shared branches — the preferred way to undo pushed work."
    },
    {
        "task": "Revert the most recent commit",
        "command": "git revert HEAD",
        "explanation": "Generates an inverse commit undoing the latest change without rewriting history. Safe to push to shared branches."
    },
    {
        "task": "Squash the last N commits into one",
        "command": "git reset --soft HEAD~N && git commit -m \"combined message\"",
        "explanation": "Collapses the last N commits into a single new commit, keeping all changes staged. DANGER if those commits were pushed — rewrites history."
    },
    {
        "task": "Squash commits interactively",
        "command": "git rebase -i HEAD~N",
        "explanation": "Opens an editor to reorder, squash, fixup, or drop the last N commits. DANGER if already pushed — rewrites history and requires a force push."
    },
    {
        "task": "Stash your current changes",
        "command": "git stash   (or: git stash push -m \"message\")",
        "explanation": "Shelves tracked changes and reverts the working tree to a clean state so you can switch tasks. Safe — retrievable later."
    },
    {
        "task": "Stash including untracked files",
        "command": "git stash -u",
        "explanation": "Stashes both tracked and untracked files. Safe; ignored files stay put unless you add -a."
    },
    {
        "task": "Reapply your most recent stash",
        "command": "git stash pop   (keep it: git stash apply)",
        "explanation": "Restores stashed changes; pop also deletes the stash, apply keeps it. Safe, though re-applying may produce merge conflicts."
    },
    {
        "task": "List and inspect stashes",
        "command": "git stash list   (then: git stash show -p stash@{0})",
        "explanation": "Shows all saved stashes and lets you view a stash's diff before applying. Read-only and safe."
    },
    {
        "task": "Drop or clear stashes",
        "command": "git stash drop stash@{0}   (all: git stash clear)",
        "explanation": "Deletes a single stash or all of them. DANGER: dropped stashes are hard to recover; clear wipes every stash."
    },
    {
        "task": "See commit history",
        "command": "git log --oneline --graph --decorate --all",
        "explanation": "Shows a compact, visual history of commits, branches, and merges. Read-only and safe; press q to quit the pager."
    },
    {
        "task": "See the history of a specific file",
        "command": "git log --follow -p -- <file>",
        "explanation": "Shows every commit that touched a file (following renames) with its diffs. Read-only and safe."
    },
    {
        "task": "See what changed (unstaged vs working tree)",
        "command": "git diff",
        "explanation": "Shows unstaged modifications compared to the index. Read-only and safe."
    },
    {
        "task": "See what's staged for commit",
        "command": "git diff --staged   (alias: git diff --cached)",
        "explanation": "Shows the differences that will go into your next commit. Read-only and safe."
    },
    {
        "task": "Compare two branches",
        "command": "git diff <branch-a>..<branch-b>",
        "explanation": "Shows the differences between two branches or commits. Read-only and safe."
    },
    {
        "task": "See who changed each line of a file",
        "command": "git blame <file>",
        "explanation": "Annotates each line with the commit, author, and date that last modified it. Read-only and safe."
    },
    {
        "task": "Remove a file from the entire Git history",
        "command": "git filter-repo --path <file> --invert-paths   (legacy: git filter-branch or BFG Repo-Cleaner)",
        "explanation": "Purges a file (e.g. a leaked secret) from all commits. DANGER: rewrites the whole history and every commit hash; requires force push and breaks all clones. Rotate any exposed secret afterward."
    },
    {
        "task": "Stop tracking a file but keep it locally",
        "command": "git rm --cached <file>",
        "explanation": "Removes a file from version control while leaving it on disk; pair with adding it to .gitignore. Safe; the file remains in history until purged."
    },
    {
        "task": "Change a remote's URL",
        "command": "git remote set-url origin <new-url>",
        "explanation": "Points an existing remote (e.g. when switching HTTPS↔SSH or moving hosts) to a new URL. Safe; verify with git remote -v."
    },
    {
        "task": "Add a new remote",
        "command": "git remote add <name> <url>",
        "explanation": "Registers an additional remote, such as an upstream for a fork. Safe."
    },
    {
        "task": "View configured remotes",
        "command": "git remote -v",
        "explanation": "Lists remote names with their fetch and push URLs. Read-only and safe."
    },
    {
        "task": "Undo a merge that hasn't been pushed",
        "command": "git reset --hard ORIG_HEAD",
        "explanation": "Resets back to the state just before the last merge. DANGER: discards the merge and any uncommitted work; only use before pushing."
    },
    {
        "task": "Revert an already-pushed merge commit",
        "command": "git revert -m 1 <merge-commit-hash>",
        "explanation": "Undoes a pushed merge by creating an inverse commit; -m 1 keeps the first parent (usually the target branch). Safe for shared branches, but re-merging later needs care."
    },
    {
        "task": "Abort a merge with conflicts in progress",
        "command": "git merge --abort",
        "explanation": "Cancels an in-progress merge and restores the pre-merge state. Safe — returns you to where you started."
    },
    {
        "task": "Recover a deleted commit or branch",
        "command": "git reflog   (then: git checkout -b recovered <hash>  or  git reset --hard <hash>)",
        "explanation": "Reflog lists where HEAD has been, including 'lost' commits, so you can restore them. Safe to read; recovery rescues work that seemed gone."
    },
    {
        "task": "Cherry-pick a commit onto the current branch",
        "command": "git cherry-pick <commit-hash>",
        "explanation": "Applies the changes from a single commit (from another branch) onto your current branch as a new commit. Safe; may produce conflicts to resolve."
    },
    {
        "task": "Cherry-pick a range of commits",
        "command": "git cherry-pick <start>^..<end>",
        "explanation": "Applies a contiguous range of commits onto the current branch. Safe; resolve conflicts as they arise, then git cherry-pick --continue."
    },
    {
        "task": "Pull the latest changes from the remote",
        "command": "git pull --rebase origin <branch>",
        "explanation": "Fetches and replays your local commits on top of the remote's, avoiding messy merge commits. Safe; resolve any conflicts during the rebase."
    },
    {
        "task": "Force push safely after rewriting history",
        "command": "git push --force-with-lease",
        "explanation": "Overwrites the remote branch only if no one else has pushed since your last fetch. Safer than --force, but still DANGER on shared branches — coordinate first."
    },
    {
        "task": "Discard a specific commit in the middle of history",
        "command": "git rebase --onto <commit>~1 <commit> <branch>   (or drop it via git rebase -i)",
        "explanation": "Removes one commit while keeping the commits after it. DANGER: rewrites history; force push needed if already pushed."
    },
    {
        "task": "Move uncommitted changes to a new branch",
        "command": "git switch -c <new-branch>   (older Git: git checkout -b <new-branch>)",
        "explanation": "Carries your current uncommitted changes onto a fresh branch so you can commit them there instead of the current branch. Safe."
    },
    {
        "task": "Temporarily check out an old commit",
        "command": "git checkout <commit-hash>   (return with: git switch -)",
        "explanation": "Puts you in 'detached HEAD' to inspect a past state. Safe to look around, but commits made here are lost unless you create a branch first."
    },
    {
        "task": "Tag a release",
        "command": "git tag -a v1.0.0 -m \"Release 1.0.0\" && git push origin v1.0.0",
        "explanation": "Creates an annotated tag marking a release point and pushes it to the remote. Safe; tags are easy to delete and recreate if needed."
    },
    {
        "task": "Update your branch with the latest main",
        "command": "git fetch origin && git rebase origin/main",
        "explanation": "Replays your branch's commits on top of the newest main for a linear history. Safe locally; needs --force-with-lease to push if the branch was already pushed."
    }
]

REGEX_PATTERNS = [
    {
        "name": "Email address",
        "pattern": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
        "explanation": "Matches a local part (letters, digits, and common symbols), an @, a domain, and a TLD of 2+ letters. It is pragmatic, not fully RFC 5322 compliant: it rejects quoted local parts, IP-literal domains, and some valid edge cases.",
        "example": "jane.doe+news@example.co.uk"
    },
    {
        "name": "URL (http/https)",
        "pattern": "^https?:\\/\\/(?:[\\w-]+\\.)+[\\w-]+(?:\\/[^\\s]*)?$",
        "explanation": "Requires an http or https scheme, one or more dot-separated host labels, and an optional path/query. It does not validate ports, userinfo, IP hosts, or other schemes like ftp, and accepts some invalid hostnames.",
        "example": "https://www.example.com/path?id=42"
    },
    {
        "name": "IPv4 address",
        "pattern": "^(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)){3}$",
        "explanation": "Validates four octets each in the 0-255 range using alternation to bound each value. It does not handle leading zeros as octal, IPv4-in-IPv6, or CIDR suffixes.",
        "example": "192.168.1.100"
    },
    {
        "name": "Phone number (US)",
        "pattern": "^(?:\\+?1[-.\\s]?)?\\(?([2-9]\\d{2})\\)?[-.\\s]?([2-9]\\d{2})[-.\\s]?(\\d{4})$",
        "explanation": "Accepts an optional +1 country code and a NANP number with optional parentheses, dots, spaces, or dashes; area and exchange codes must start 2-9. It does not enforce every NANP reservation rule (e.g. N11 codes).",
        "example": "+1 (415) 555-2671"
    },
    {
        "name": "Date (YYYY-MM-DD)",
        "pattern": "^(\\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$",
        "explanation": "Matches ISO 8601 calendar dates with a 4-digit year, month 01-12, and day 01-31. It does not validate days-per-month or leap years, so 2023-02-31 still matches.",
        "example": "2026-06-13"
    },
    {
        "name": "Time (24-hour HH:MM)",
        "pattern": "^([01]\\d|2[0-3]):([0-5]\\d)$",
        "explanation": "Matches a 24-hour clock time with hours 00-23 and minutes 00-59. It does not include seconds or accept a single-digit hour without a leading zero.",
        "example": "23:59"
    },
    {
        "name": "Time (24-hour with optional seconds)",
        "pattern": "^([01]\\d|2[0-3]):([0-5]\\d)(:([0-5]\\d))?$",
        "explanation": "Like the basic 24-hour pattern but allows an optional :SS seconds component. It does not handle fractional seconds or a leap second (60).",
        "example": "08:30:15"
    },
    {
        "name": "Time (12-hour with AM/PM)",
        "pattern": "^(0?[1-9]|1[0-2]):[0-5]\\d\\s?([AaPp][Mm])$",
        "explanation": "Matches a 12-hour time with hours 1-12, minutes 00-59, and an AM/PM marker with optional space. It does not include seconds and allows hour without a leading zero.",
        "example": "9:05 PM"
    },
    {
        "name": "Hex color",
        "pattern": "^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$",
        "explanation": "Matches a leading # followed by 3, 4, 6, or 8 hex digits, covering shorthand, RGB, and RGBA/8-digit forms. It does not accept rgb()/hsl() function syntax or named colors.",
        "example": "#1a2b3c"
    },
    {
        "name": "Username",
        "pattern": "^[a-zA-Z0-9_]{3,16}$",
        "explanation": "Allows letters, digits, and underscores with a length of 3 to 16 characters. It forbids spaces, dots, and hyphens; adjust the class and length bounds to fit your platform's rules.",
        "example": "cool_user_99"
    },
    {
        "name": "Password strength (strong)",
        "pattern": "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^\\w\\s]).{8,}$",
        "explanation": "Uses lookaheads to require at least one lowercase, one uppercase, one digit, and one special (non-word, non-space) character, with a minimum length of 8. It cannot detect dictionary words or reused passwords and treats Unicode letters as non-matching for the case classes.",
        "example": "P@ssw0rd1"
    },
    {
        "name": "Whitespace (any)",
        "pattern": "\\s+",
        "explanation": "Matches one or more whitespace characters including spaces, tabs, and newlines. Use it unanchored for find/replace (e.g. collapsing runs of spaces); anchor it if you need a whole string of only whitespace.",
        "example": "\t  \n"
    },
    {
        "name": "Digits only",
        "pattern": "^\\d+$",
        "explanation": "Matches a string consisting entirely of one or more ASCII digits. In some engines \\d also matches Unicode digits unless the ASCII/Unicode flag is set, and it does not allow signs or decimal points.",
        "example": "00420315"
    },
    {
        "name": "Letters only",
        "pattern": "^[A-Za-z]+$",
        "explanation": "Matches a string of one or more ASCII letters with no digits, spaces, or punctuation. It excludes accented and non-Latin letters; use \\p{L} with the Unicode flag for those.",
        "example": "HelloWorld"
    },
    {
        "name": "Alphanumeric",
        "pattern": "^[A-Za-z0-9]+$",
        "explanation": "Matches a string containing only ASCII letters and digits. It excludes spaces, underscores, hyphens, and Unicode characters.",
        "example": "abc123XYZ"
    },
    {
        "name": "HTML tag",
        "pattern": "<([a-zA-Z][a-zA-Z0-9]*)\\b[^>]*>(.*?)<\\/\\1>",
        "explanation": "Matches a simple opening tag, its inner content, and a matching closing tag using a backreference to the tag name. It is unreliable for nested same-name tags, self-closing tags, and comments; HTML should generally be parsed, not regexed.",
        "example": "<p class=\"lead\">Hello</p>"
    },
    {
        "name": "Slug (URL)",
        "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
        "explanation": "Matches lowercase, hyphen-separated word groups with no leading, trailing, or doubled hyphens. It rejects uppercase, underscores, and spaces, which is typical for SEO-friendly URLs.",
        "example": "my-first-blog-post"
    },
    {
        "name": "US ZIP code",
        "pattern": "^\\d{5}(?:-\\d{4})?$",
        "explanation": "Matches a 5-digit ZIP with an optional 4-digit ZIP+4 extension. It validates format only, not whether the ZIP actually exists.",
        "example": "94103-1234"
    },
    {
        "name": "Credit card number",
        "pattern": "^(?:4\\d{12}(?:\\d{3})?|5[1-5]\\d{14}|3[47]\\d{13}|6(?:011|5\\d{2})\\d{12})$",
        "explanation": "Matches the digit patterns of Visa, Mastercard, Amex, and Discover (no spaces or dashes). It checks prefix and length only, not the Luhn checksum, so a structurally valid but invalid number can still match.",
        "example": "4111111111111111"
    },
    {
        "name": "UUID (v4)",
        "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
        "explanation": "Matches a canonical UUID where the version nibble is 4 and the variant nibble is 8, 9, a, or b. For any UUID version, replace the '4' and variant class with [0-9a-fA-F].",
        "example": "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
    },
    {
        "name": "IP with port",
        "pattern": "^(?:(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.){3}(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d):(?:6553[0-5]|655[0-2]\\d|65[0-4]\\d{2}|6[0-4]\\d{3}|[1-5]\\d{4}|[1-9]\\d{0,3})$",
        "explanation": "Validates an IPv4 address followed by a colon and a port in the 1-65535 range. It does not accept port 0 and does not handle IPv6 host:port (which needs brackets).",
        "example": "127.0.0.1:8080"
    },
    {
        "name": "Domain name",
        "pattern": "^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,}$",
        "explanation": "Matches dot-separated labels (1-63 chars, no leading/trailing hyphen) ending in an alphabetic TLD of 2+ characters. It does not validate punycode/IDN directly or enforce the 253-char total length limit.",
        "example": "sub.example-site.com"
    },
    {
        "name": "IPv6 address",
        "pattern": "^(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$",
        "explanation": "Matches a fully expanded IPv6 address of eight 16-bit hex groups separated by colons. It does not support :: zero-compression or embedded IPv4 suffixes, so many valid shortened addresses won't match.",
        "example": "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
    },
    {
        "name": "MAC address",
        "pattern": "^(?:[0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$",
        "explanation": "Matches six hex byte pairs separated by colons or hyphens. It does not accept the dotted Cisco notation (e.g. aaaa.bbbb.cccc) and allows mixing of separators within one string.",
        "example": "00:1A:2B:3C:4D:5E"
    },
    {
        "name": "Date (MM/DD/YYYY)",
        "pattern": "^(0[1-9]|1[0-2])\\/(0[1-9]|[12]\\d|3[01])\\/\\d{4}$",
        "explanation": "Matches US-style dates with month 01-12, day 01-31, and a 4-digit year separated by slashes. It does not enforce valid days per month or leap years.",
        "example": "06/13/2026"
    },
    {
        "name": "Date and time (ISO 8601)",
        "pattern": "^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])T([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z|[+-]([01]\\d|2[0-3]):[0-5]\\d)?$",
        "explanation": "Matches an ISO 8601 timestamp with date, T separator, time, optional fractional seconds, and optional Z or numeric timezone offset. It does not validate calendar correctness like leap years.",
        "example": "2026-06-13T08:30:00Z"
    },
    {
        "name": "Hashtag",
        "pattern": "#[A-Za-z0-9_]+",
        "explanation": "Matches a # followed by one or more letters, digits, or underscores. It does not exclude purely numeric tags (which most platforms ignore) or support Unicode hashtags without the u flag and \\p{L}.",
        "example": "#OpenSource2026"
    },
    {
        "name": "@mention",
        "pattern": "(?:^|\\s)@([A-Za-z0-9_]{1,15})\\b",
        "explanation": "Captures a handle of up to 15 word characters preceded by start-of-string or whitespace, mirroring Twitter-style rules. The leading whitespace requirement avoids matching emails; the captured group holds the bare handle.",
        "example": " @octocat"
    },
    {
        "name": "Latitude/longitude pair",
        "pattern": "^[-+]?(?:90(?:\\.0+)?|[1-8]?\\d(?:\\.\\d+)?),\\s*[-+]?(?:180(?:\\.0+)?|1[0-7]\\d(?:\\.\\d+)?|\\d{1,2}(?:\\.\\d+)?)$",
        "explanation": "Validates a latitude in [-90, 90] and longitude in [-180, 180] separated by a comma. It checks numeric ranges but not precision or that the coordinate is on land.",
        "example": "-33.8688, 151.2093"
    },
    {
        "name": "Currency amount (USD)",
        "pattern": "^\\$?(?:\\d{1,3}(?:,\\d{3})*|\\d+)(?:\\.\\d{2})?$",
        "explanation": "Matches an optional $ sign, an integer part with optional thousands separators, and an optional two-decimal cents portion. It does not validate that comma grouping is consistent across all locales or handle negative/parenthesized amounts.",
        "example": "$1,250.00"
    },
    {
        "name": "Semantic version (SemVer)",
        "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-[0-9A-Za-z.-]+)?(?:\\+[0-9A-Za-z.-]+)?$",
        "explanation": "Matches MAJOR.MINOR.PATCH with no leading zeros plus optional pre-release and build-metadata segments per the SemVer spec. It does not deeply validate the internal structure of dot-separated pre-release identifiers.",
        "example": "2.4.1-rc.1+build.5"
    },
    {
        "name": "Strong slug with optional trailing slash",
        "pattern": "^\\/?[a-z0-9]+(?:-[a-z0-9]+)*\\/?$",
        "explanation": "Matches a single path slug allowing optional leading and trailing slashes around a hyphenated lowercase token. It matches one segment only, not multi-level paths.",
        "example": "/about-us/"
    },
    {
        "name": "Integer (signed)",
        "pattern": "^[+-]?\\d+$",
        "explanation": "Matches an optional leading + or - sign followed by one or more digits. It allows leading zeros and does not bound the magnitude or accept thousands separators.",
        "example": "-2048"
    },
    {
        "name": "Decimal / float (signed)",
        "pattern": "^[+-]?(?:\\d+\\.?\\d*|\\.\\d+)(?:[eE][+-]?\\d+)?$",
        "explanation": "Matches signed decimals and floats including optional fractional part, leading-dot numbers, and scientific notation. It does not reject ambiguous forms like a bare '.' because each branch requires at least one digit.",
        "example": "-3.14e-2"
    },
    {
        "name": "Word boundary whole word",
        "pattern": "\\bword\\b",
        "explanation": "Matches the literal sequence 'word' only when surrounded by word boundaries, so it won't match inside 'password' or 'wording'. Replace 'word' with your target term; boundaries are zero-width and consume no characters.",
        "example": "a single word here"
    },
    {
        "name": "Leading/trailing whitespace (trim)",
        "pattern": "^\\s+|\\s+$",
        "explanation": "Matches a run of whitespace at the start OR end of a string; apply it with the global flag in a replace to trim both sides. It does not collapse internal whitespace.",
        "example": "   hello   "
    },
    {
        "name": "Blank or whitespace-only line",
        "pattern": "^\\s*$",
        "explanation": "Matches a line that is empty or contains only whitespace; pair it with the multiline flag to find blank lines in a document. With multiline off it matches only a wholly blank string.",
        "example": "   "
    },
    {
        "name": "HTML/XML comment",
        "pattern": "<!--[\\s\\S]*?-->",
        "explanation": "Matches an HTML or XML comment using a lazy [\\s\\S] to span multiple lines without needing the dotall flag. It can be fooled by the rare invalid comments containing '--' internally.",
        "example": "<!-- TODO: fix layout -->"
    },
    {
        "name": "US Social Security Number",
        "pattern": "^(?!000|666|9\\d\\d)\\d{3}-(?!00)\\d{2}-(?!0000)\\d{4}$",
        "explanation": "Matches the AAA-GG-SSSS format while excluding invalid area numbers (000, 666, 900-999) and all-zero group or serial parts via negative lookaheads. It enforces formatting rules, not whether the SSN was actually issued.",
        "example": "123-45-6789"
    },
    {
        "name": "Twitter/X handle",
        "pattern": "^@?(\\w){1,15}$",
        "explanation": "Matches an optional @ followed by 1 to 15 word characters (letters, digits, underscore), the platform's handle constraint. It does not forbid handles that are reserved or all-numeric.",
        "example": "@jack"
    },
    {
        "name": "File path (Unix)",
        "pattern": "^(\\/[^\\/\\0]+)+\\/?$",
        "explanation": "Matches an absolute Unix path of one or more slash-separated non-empty segments with an optional trailing slash. It rejects the root '/' alone and does not validate that the path exists or handle escaped spaces specially.",
        "example": "/usr/local/bin/node"
    },
    {
        "name": "Windows file path",
        "pattern": "^[a-zA-Z]:\\\\(?:[^\\\\\\/:*?\"<>|\\r\\n]+\\\\?)*$",
        "explanation": "Matches a drive-letter path using backslashes and forbidding the characters illegal in Windows filenames. It does not handle UNC (\\\\server\\share) paths or extended-length \\\\?\\ prefixes.",
        "example": "C:\\Users\\guada\\file.txt"
    },
    {
        "name": "Base64 string",
        "pattern": "^(?:[A-Za-z0-9+\\/]{4})*(?:[A-Za-z0-9+\\/]{2}==|[A-Za-z0-9+\\/]{3}=)?$",
        "explanation": "Matches standard Base64 in groups of four with correct trailing padding of one or two '=' characters. It does not validate URL-safe Base64 (-/_) or that the decoded content is meaningful, and it accepts the empty string.",
        "example": "SGVsbG8gV29ybGQh"
    },
    {
        "name": "Markdown link",
        "pattern": "\\[([^\\]]+)\\]\\(([^)\\s]+)(?:\\s+\"[^\"]*\")?\\)",
        "explanation": "Captures the link text and URL of a Markdown inline link, with optional quoted title. It struggles with nested brackets in the text or parentheses inside the URL.",
        "example": "[Anthropic](https://anthropic.com \"home\")"
    },
    {
        "name": "Emoji (basic ranges)",
        "pattern": "[\\u{1F300}-\\u{1FAFF}\\u{2600}-\\u{27BF}]",
        "explanation": "Matches characters in common emoji Unicode blocks; requires the u flag in JavaScript for the \\u{...} syntax. It does not handle multi-codepoint emoji like skin-tone modifiers or ZWJ sequences as single units.",
        "example": "🚀"
    }
]

LINUX_COMMANDS = [
    {
        "name": "chmod 777 (full permissions)",
        "command": "chmod 777 file",
        "explanation": "Grants read, write, and execute to owner, group, and everyone. Caution: 777 is a security risk—anyone can modify/run the file. Avoid on web roots or shared systems; prefer the least-permissive mode that works."
    },
    {
        "name": "chmod 755 (standard executable/dir)",
        "command": "chmod 755 file",
        "explanation": "Owner gets full access (rwx); group and others get read+execute. The safe default for scripts and directories. Use 644 for non-executable files instead."
    },
    {
        "name": "chmod +x (make executable)",
        "command": "chmod +x script.sh",
        "explanation": "Adds the execute bit for all who can read the file, so you can run ./script.sh. Add it only to files meant to be run; combine with ./ to execute from the current directory."
    },
    {
        "name": "chmod recursively",
        "command": "chmod -R 755 mydir/",
        "explanation": "Applies the mode to a directory and everything inside it. Caution: applying 755 to plain files makes them executable; prefer find with -type to set dirs and files separately."
    },
    {
        "name": "chmod files vs dirs separately",
        "command": "find . -type d -exec chmod 755 {} \\; && find . -type f -exec chmod 644 {} \\;",
        "explanation": "Sets directories to 755 and files to 644 in one pass—the correct way to fix permissions on a tree without making files executable."
    },
    {
        "name": "chown (change owner)",
        "command": "sudo chown user:group file",
        "explanation": "Changes the owning user and group. Add -R to recurse into a directory. Usually needs sudo; double-check the path before recursing to avoid locking yourself out of files."
    },
    {
        "name": "chown recursively",
        "command": "sudo chown -R www-data:www-data /var/www",
        "explanation": "Reassigns ownership of a whole tree, common for web servers. Caution: running on the wrong directory (e.g. /) can break the system; verify the path first."
    },
    {
        "name": "chgrp (change group)",
        "command": "chgrp -R developers /project",
        "explanation": "Changes only the group ownership, leaving the owner intact. Useful for shared team directories; pair with setgid (chmod g+s) so new files inherit the group."
    },
    {
        "name": "Find files by name",
        "command": "find /path -name \"*.log\"",
        "explanation": "Searches recursively for files matching the pattern. Quote the pattern so the shell doesn't expand it. Use -iname for case-insensitive matching."
    },
    {
        "name": "Find and delete files",
        "command": "find . -name \"*.tmp\" -delete",
        "explanation": "Finds matching files and removes them. Caution: deletion is permanent—run the command without -delete first to preview what will be removed."
    },
    {
        "name": "Find and run a command on results",
        "command": "find . -name \"*.jpg\" -exec convert {} {}.png \\;",
        "explanation": "Runs a command on each match; {} is the filename and \\; ends the command. Use + instead of \\; to batch many files per invocation for speed."
    },
    {
        "name": "Find files by size",
        "command": "find . -type f -size +100M",
        "explanation": "Lists files larger than 100 megabytes. Use -size -1k for small files or c/M/G suffixes. Great for hunting down disk hogs before cleanup."
    },
    {
        "name": "Find files modified recently",
        "command": "find . -type f -mtime -7",
        "explanation": "Finds files modified in the last 7 days (-mtime -7). Use +7 for older than 7 days, and -mmin for minutes. Handy for backups and audits."
    },
    {
        "name": "Find empty files and directories",
        "command": "find . -empty",
        "explanation": "Locates zero-byte files and empty directories. Add -type d to limit to directories or -delete to clean them up (preview first)."
    },
    {
        "name": "Grep recursively",
        "command": "grep -r \"searchterm\" .",
        "explanation": "Searches all files under the current directory for the text. Add -n for line numbers and -i for case-insensitive. Use -rI to skip binary files."
    },
    {
        "name": "Grep with line numbers and context",
        "command": "grep -rn -C 3 \"TODO\" src/",
        "explanation": "Shows matches with 3 lines of context above and below (-C). Use -A/-B for after/before only. -n prints line numbers for quick navigation."
    },
    {
        "name": "Grep only file names",
        "command": "grep -rl \"pattern\" .",
        "explanation": "Lists just the file names that contain a match, not the lines. Useful for piping into other commands. Use -L to list files that do NOT match."
    },
    {
        "name": "Grep invert match",
        "command": "grep -v \"DEBUG\" app.log",
        "explanation": "Prints lines that do NOT contain the pattern. Chain greps to filter logs. Combine with -i for case-insensitive exclusion."
    },
    {
        "name": "Grep extended regex",
        "command": "grep -E \"error|warn|fail\" app.log",
        "explanation": "Enables extended regular expressions so | means OR without escaping. Equivalent to egrep. Anchor with ^ and $ for whole-line matches."
    },
    {
        "name": "Tar extract gzip archive",
        "command": "tar -xzvf archive.tar.gz",
        "explanation": "Extracts a gzip-compressed tarball: x=extract, z=gzip, v=verbose, f=file. Drop z for plain .tar, use -xjvf for .tar.bz2 and -xJvf for .tar.xz."
    },
    {
        "name": "Tar extract to a directory",
        "command": "tar -xzvf archive.tar.gz -C /target/dir",
        "explanation": "Extracts into the specified directory instead of the current one. The target directory must already exist. Useful to avoid cluttering your cwd."
    },
    {
        "name": "Tar create gzip archive",
        "command": "tar -czvf archive.tar.gz folder/",
        "explanation": "Creates a compressed archive of a folder: c=create, z=gzip, v=verbose, f=file. Put -f last so the filename is read correctly. Use .tgz as a shorthand extension."
    },
    {
        "name": "Tar list archive contents",
        "command": "tar -tzvf archive.tar.gz",
        "explanation": "Lists what's inside an archive without extracting (t=list). Always inspect untrusted archives this way first to avoid files escaping into unexpected paths."
    },
    {
        "name": "Tar exclude files",
        "command": "tar -czvf site.tar.gz site/ --exclude='*.log' --exclude=node_modules",
        "explanation": "Creates an archive skipping matched paths. Place --exclude before the source on some systems. Great for backups that skip caches and logs."
    },
    {
        "name": "ls with options",
        "command": "ls -lah",
        "explanation": "Long listing (-l) with hidden files (-a) and human-readable sizes (-h). The most common everyday ls combo. Add -t to sort by time, -r to reverse."
    },
    {
        "name": "ls sorted by modification time",
        "command": "ls -lt",
        "explanation": "Lists files newest-first by modification time. Add -r to put the oldest first. Combine with head to see the most recently changed files."
    },
    {
        "name": "ls sorted by size",
        "command": "ls -lhS",
        "explanation": "Sorts the long listing by size, largest first (-S), with human-readable units. Quick way to spot big files in one directory (non-recursive)."
    },
    {
        "name": "Kill a process by port",
        "command": "kill -9 $(lsof -t -i:3000)",
        "explanation": "Finds the PID listening on port 3000 and force-kills it. -9 is SIGKILL (no cleanup)—try a plain kill first. On some systems use fuser -k 3000/tcp instead."
    },
    {
        "name": "Find what is using a port",
        "command": "lsof -i :8080",
        "explanation": "Shows the process, PID, and user bound to port 8080. Run with sudo to see processes you don't own. Use ss -ltnp as a faster alternative."
    },
    {
        "name": "Kill a process by name",
        "command": "pkill -f myprocess",
        "explanation": "Kills all processes whose command line matches the pattern (-f matches full args). Caution: a broad pattern can kill unintended processes—test with pgrep -f first."
    },
    {
        "name": "Kill process by name (killall)",
        "command": "killall firefox",
        "explanation": "Terminates all processes with the exact name 'firefox'. Unlike pkill it matches the process name, not the full command line. Add -9 to force if it won't stop."
    },
    {
        "name": "ps aux (list all processes)",
        "command": "ps aux",
        "explanation": "Shows every running process with user, PID, CPU, and memory. Pipe to grep to find one: ps aux | grep nginx. Use --sort=-%mem to rank by memory."
    },
    {
        "name": "ps top CPU consumers",
        "command": "ps aux --sort=-%cpu | head",
        "explanation": "Lists processes ordered by CPU usage, highest first, showing the top handful. Swap %cpu for %mem to find memory hogs. A quick triage when a box is busy."
    },
    {
        "name": "pgrep (find PIDs by name)",
        "command": "pgrep -fl node",
        "explanation": "Prints PIDs (and with -l, names) of matching processes without killing them. Safer than pkill for verifying what you're about to target."
    },
    {
        "name": "df -h (disk free)",
        "command": "df -h",
        "explanation": "Shows disk space per mounted filesystem in human-readable units. Watch the Use% column for full volumes. Add -i to check inode exhaustion instead of bytes."
    },
    {
        "name": "du -sh (directory size)",
        "command": "du -sh /path",
        "explanation": "Prints the total size of a directory in human-readable form (-s summary, -h human). Drop -s to see each subitem. Add -c on multiple paths for a grand total."
    },
    {
        "name": "du largest subdirectories",
        "command": "du -h --max-depth=1 . | sort -h",
        "explanation": "Shows the size of each immediate subdirectory, sorted smallest to largest. The fastest way to find where disk space went. Run as root for protected paths."
    },
    {
        "name": "top (live process monitor)",
        "command": "top",
        "explanation": "Real-time view of CPU, memory, and processes. Press M to sort by memory, P by CPU, k to kill a PID, q to quit. The classic always-available monitor."
    },
    {
        "name": "htop (interactive monitor)",
        "command": "htop",
        "explanation": "A friendlier, colorized top with scrolling, mouse support, and easy process killing (F9). Install via your package manager if missing; great for quick system triage."
    },
    {
        "name": "scp a file to a remote host",
        "command": "scp file.txt user@host:/remote/path/",
        "explanation": "Securely copies a file over SSH to a remote machine. Add -r to copy directories and -P (capital) to set a non-default port. Trailing slash means the target is a directory."
    },
    {
        "name": "scp a file from a remote host",
        "command": "scp user@host:/remote/file.txt .",
        "explanation": "Pulls a file from a remote server to your current directory. Reverse of an upload. Use -r for directories; quote remote paths containing spaces or globs."
    },
    {
        "name": "rsync (sync directories)",
        "command": "rsync -avh source/ dest/",
        "explanation": "Efficiently mirrors directories, copying only changes (-a archive, -v verbose, -h human). A trailing slash on source copies its contents, not the folder itself—mind it carefully."
    },
    {
        "name": "rsync over SSH with progress",
        "command": "rsync -avz --progress -e ssh local/ user@host:/remote/",
        "explanation": "Syncs to a remote host with compression (-z) and a live progress bar. Add --delete to mirror exactly (removes extra files on the destination)—use with care."
    },
    {
        "name": "rsync dry run",
        "command": "rsync -avhn --delete source/ dest/",
        "explanation": "The -n (dry-run) flag shows what would change without touching anything—essential before using --delete. Review the output, then rerun without -n to apply."
    },
    {
        "name": "ssh into a server",
        "command": "ssh user@host",
        "explanation": "Opens a secure shell on a remote machine. Add -p PORT for a non-standard port and -i key.pem for a specific identity file. First connection asks you to trust the host key."
    },
    {
        "name": "ssh run a single remote command",
        "command": "ssh user@host 'df -h'",
        "explanation": "Executes one command on the remote host and returns immediately. Great for scripts and checks. Quote the command so your local shell doesn't expand it."
    },
    {
        "name": "ssh port forwarding (tunnel)",
        "command": "ssh -L 8080:localhost:80 user@host",
        "explanation": "Forwards your local port 8080 to port 80 on the remote side, letting you reach remote services locally. Use -N to forward without opening a shell."
    },
    {
        "name": "ssh copy your public key",
        "command": "ssh-copy-id user@host",
        "explanation": "Installs your public key on the remote server for password-free login. Run once per host. Requires an existing key pair (generate with ssh-keygen first)."
    },
    {
        "name": "curl download a file",
        "command": "curl -O https://example.com/file.zip",
        "explanation": "Downloads a file keeping its remote name (-O). Use -o name to rename, and -L to follow redirects. Add -C - to resume an interrupted download."
    },
    {
        "name": "curl an API (headers/JSON)",
        "command": "curl -s -H \"Content-Type: application/json\" -d '{\"k\":\"v\"}' https://api.example.com",
        "explanation": "Sends a POST with JSON body (-d) and a header (-H); -s silences the progress meter. Add -X GET/PUT/DELETE to change the method and -i to see response headers."
    },
    {
        "name": "wget download a file",
        "command": "wget https://example.com/file.zip",
        "explanation": "Downloads a URL to the current directory. Add -c to resume, -O name to rename. Unlike curl it follows redirects and saves files by default."
    },
    {
        "name": "wget mirror a website",
        "command": "wget -r -np -k https://example.com",
        "explanation": "Recursively downloads a site (-r), staying within the path (-np = no parent) and rewriting links for offline browsing (-k). Be polite—add --wait to avoid hammering servers."
    },
    {
        "name": "Create a symlink (ln -s)",
        "command": "ln -s /path/to/target linkname",
        "explanation": "Creates a symbolic link pointing to the target. The target path should usually be absolute so the link survives moves. Add -f to overwrite an existing link."
    },
    {
        "name": "cat (view a file)",
        "command": "cat file.txt",
        "explanation": "Prints a file's entire contents to the terminal. Use -n to number lines. For large files prefer less so you can scroll instead of flooding the screen."
    },
    {
        "name": "head (first lines)",
        "command": "head -n 20 file.txt",
        "explanation": "Shows the first 20 lines of a file (default 10). Handy for peeking at CSV headers or log starts. Use -c for bytes instead of lines."
    },
    {
        "name": "tail (last lines)",
        "command": "tail -n 50 file.txt",
        "explanation": "Shows the last 50 lines of a file. The go-to for checking recent log entries. Combine with head to grab a middle slice."
    },
    {
        "name": "tail -f (follow a log)",
        "command": "tail -f /var/log/syslog",
        "explanation": "Streams new lines as they're appended—essential for watching live logs. Use -F to keep following through log rotation. Ctrl+C to stop."
    },
    {
        "name": "awk print a column",
        "command": "awk '{print $2}' file.txt",
        "explanation": "Prints the second whitespace-separated field of each line. Use -F',' to split on commas (CSV). The Swiss-army knife for column extraction."
    },
    {
        "name": "awk filter and compute",
        "command": "awk -F',' '$3 > 100 {sum+=$3} END {print sum}' data.csv",
        "explanation": "Splits on commas, keeps rows where column 3 exceeds 100, sums that column, and prints the total at the end. Shows awk's filter + aggregate power in one line."
    },
    {
        "name": "sed replace text in place",
        "command": "sed -i 's/old/new/g' file.txt",
        "explanation": "Replaces every 'old' with 'new' across the file, editing it directly (-i). Caution: -i overwrites with no undo—back up or use sed -i.bak to keep a copy."
    },
    {
        "name": "sed replace across many files",
        "command": "grep -rl 'old' . | xargs sed -i 's/old/new/g'",
        "explanation": "Finds files containing 'old' and rewrites them all in place. Powerful but irreversible—run the grep alone first and commit to version control before applying."
    },
    {
        "name": "sed delete lines",
        "command": "sed -i '/pattern/d' file.txt",
        "explanation": "Deletes every line matching the pattern from the file. Use '2d' to delete a specific line number or '2,5d' for a range. Test without -i first."
    },
    {
        "name": "sort a file",
        "command": "sort file.txt",
        "explanation": "Sorts lines alphabetically. Add -n for numeric, -r to reverse, -k2 to sort by the second field, and -h for human-readable sizes (e.g. 1K, 2M)."
    },
    {
        "name": "sort and unique counts",
        "command": "sort file.txt | uniq -c | sort -nr",
        "explanation": "Counts how often each line appears and ranks them most-frequent first. uniq needs sorted input, hence the leading sort. A classic log-frequency one-liner."
    },
    {
        "name": "uniq remove duplicates",
        "command": "sort file.txt | uniq",
        "explanation": "Collapses adjacent duplicate lines after sorting, leaving unique lines. Use uniq -d to show only duplicates or uniq -u for lines that appear exactly once."
    },
    {
        "name": "wc count lines/words/bytes",
        "command": "wc -l file.txt",
        "explanation": "Counts lines (-l); use -w for words and -c for bytes. Pipe into it to count results, e.g. grep -r foo . | wc -l for number of matches."
    },
    {
        "name": "history (command history)",
        "command": "history",
        "explanation": "Lists your previously run commands with numbers. Run !123 to repeat command 123, or !! to rerun the last one. Pipe to grep to search: history | grep ssh."
    },
    {
        "name": "Reverse search history",
        "command": "Ctrl + R then type",
        "explanation": "Interactive reverse search through past commands as you type. Press Ctrl+R again to cycle older matches, Enter to run, or arrow keys to edit first."
    },
    {
        "name": "Set an environment variable",
        "command": "export VAR=value",
        "explanation": "Sets a variable for the current shell and child processes. It's temporary—add the line to ~/.bashrc or ~/.profile to make it persist across sessions."
    },
    {
        "name": "View environment variables",
        "command": "printenv",
        "explanation": "Prints all environment variables, or one with printenv PATH. Use env to see the same, and echo $VAR to inspect a single value inline."
    },
    {
        "name": "Run command with a temp env var",
        "command": "VAR=value command",
        "explanation": "Sets a variable only for that single command's run, without exporting it to your shell. Common for one-off configs like DEBUG=1 npm test."
    },
    {
        "name": "Edit crontab (scheduled jobs)",
        "command": "crontab -e",
        "explanation": "Opens your personal cron table to schedule recurring jobs. Format is 'min hour day month weekday command'. Use crontab -l to view and -r to remove all (careful—no confirmation)."
    },
    {
        "name": "Cron job example (every day 2am)",
        "command": "0 2 * * * /path/to/backup.sh",
        "explanation": "A crontab line that runs the script daily at 02:00. Fields: minute hour day-of-month month day-of-week. Redirect output (>> log 2>&1) since cron has no terminal."
    },
    {
        "name": "free -h (memory usage)",
        "command": "free -h",
        "explanation": "Shows total, used, and available RAM and swap in human-readable units. Look at the 'available' column for what apps can actually use. Add -s 2 to refresh every 2 seconds."
    },
    {
        "name": "netstat listening ports",
        "command": "netstat -tulpn",
        "explanation": "Lists TCP/UDP listening ports with the owning program (-t tcp, -u udp, -l listening, -p program, -n numeric). Needs sudo to see all PIDs. Deprecated on some systems—use ss."
    },
    {
        "name": "ss listening ports (modern)",
        "command": "ss -tulpn",
        "explanation": "The faster modern replacement for netstat, same flags. Shows which processes listen on which ports. Run with sudo to reveal program names for all sockets."
    },
    {
        "name": "uptime and load average",
        "command": "uptime",
        "explanation": "Shows how long the system has run and the 1/5/15-minute load averages. Compare load to your CPU core count—load above the core count means the system is saturated."
    },
    {
        "name": "watch (repeat a command)",
        "command": "watch -n 2 'df -h'",
        "explanation": "Reruns a command every 2 seconds and shows the latest output in place—great for monitoring changing values. Add -d to highlight differences. Ctrl+C to stop."
    },
    {
        "name": "ln hard link",
        "command": "ln target linkname",
        "explanation": "Creates a hard link (a second name for the same file data) rather than a symlink. Works only within one filesystem and not for directories. The data persists until all links are removed."
    },
    {
        "name": "xargs (build commands from input)",
        "command": "find . -name '*.log' | xargs rm",
        "explanation": "Feeds piped items as arguments to a command. Use -0 with find -print0 to handle spaces safely, and -n1/-P for batching and parallelism. Powerful—double-check destructive commands."
    },
    {
        "name": "ln update existing symlink",
        "command": "ln -sfn /new/target linkname",
        "explanation": "Re-points an existing symlink atomically: -s symbolic, -f force overwrite, -n treat the link itself (not its target dir) as the file. The safe way to swap a 'current' release link."
    }
]
