"""Vetted ISO 3166 country and ISO 4217 currency datasets for pSEO clusters.
Generated by scripts/gen_pseo_iso.py from a parallel-agent workflow and
anchor-validated. Do not hand-edit; regenerate from the workflow output."""
from __future__ import annotations

COUNTRIES = [
    {
        "name": "Afghanistan",
        "iso2": "AF",
        "iso3": "AFG",
        "numeric": "004",
        "dialing": "+93",
        "capital": "Kabul",
        "region": "Asia"
    },
    {
        "name": "Albania",
        "iso2": "AL",
        "iso3": "ALB",
        "numeric": "008",
        "dialing": "+355",
        "capital": "Tirana",
        "region": "Europe"
    },
    {
        "name": "Algeria",
        "iso2": "DZ",
        "iso3": "DZA",
        "numeric": "012",
        "dialing": "+213",
        "capital": "Algiers",
        "region": "Africa"
    },
    {
        "name": "Andorra",
        "iso2": "AD",
        "iso3": "AND",
        "numeric": "020",
        "dialing": "+376",
        "capital": "Andorra la Vella",
        "region": "Europe"
    },
    {
        "name": "Angola",
        "iso2": "AO",
        "iso3": "AGO",
        "numeric": "024",
        "dialing": "+244",
        "capital": "Luanda",
        "region": "Africa"
    },
    {
        "name": "Antigua and Barbuda",
        "iso2": "AG",
        "iso3": "ATG",
        "numeric": "028",
        "dialing": "+1",
        "capital": "Saint John's",
        "region": "North America"
    },
    {
        "name": "Argentina",
        "iso2": "AR",
        "iso3": "ARG",
        "numeric": "032",
        "dialing": "+54",
        "capital": "Buenos Aires",
        "region": "South America"
    },
    {
        "name": "Armenia",
        "iso2": "AM",
        "iso3": "ARM",
        "numeric": "051",
        "dialing": "+374",
        "capital": "Yerevan",
        "region": "Asia"
    },
    {
        "name": "Australia",
        "iso2": "AU",
        "iso3": "AUS",
        "numeric": "036",
        "dialing": "+61",
        "capital": "Canberra",
        "region": "Oceania"
    },
    {
        "name": "Austria",
        "iso2": "AT",
        "iso3": "AUT",
        "numeric": "040",
        "dialing": "+43",
        "capital": "Vienna",
        "region": "Europe"
    },
    {
        "name": "Azerbaijan",
        "iso2": "AZ",
        "iso3": "AZE",
        "numeric": "031",
        "dialing": "+994",
        "capital": "Baku",
        "region": "Asia"
    },
    {
        "name": "Bahamas",
        "iso2": "BS",
        "iso3": "BHS",
        "numeric": "044",
        "dialing": "+1",
        "capital": "Nassau",
        "region": "North America"
    },
    {
        "name": "Bahrain",
        "iso2": "BH",
        "iso3": "BHR",
        "numeric": "048",
        "dialing": "+973",
        "capital": "Manama",
        "region": "Asia"
    },
    {
        "name": "Bangladesh",
        "iso2": "BD",
        "iso3": "BGD",
        "numeric": "050",
        "dialing": "+880",
        "capital": "Dhaka",
        "region": "Asia"
    },
    {
        "name": "Barbados",
        "iso2": "BB",
        "iso3": "BRB",
        "numeric": "052",
        "dialing": "+1",
        "capital": "Bridgetown",
        "region": "North America"
    },
    {
        "name": "Belarus",
        "iso2": "BY",
        "iso3": "BLR",
        "numeric": "112",
        "dialing": "+375",
        "capital": "Minsk",
        "region": "Europe"
    },
    {
        "name": "Belgium",
        "iso2": "BE",
        "iso3": "BEL",
        "numeric": "056",
        "dialing": "+32",
        "capital": "Brussels",
        "region": "Europe"
    },
    {
        "name": "Belize",
        "iso2": "BZ",
        "iso3": "BLZ",
        "numeric": "084",
        "dialing": "+501",
        "capital": "Belmopan",
        "region": "North America"
    },
    {
        "name": "Benin",
        "iso2": "BJ",
        "iso3": "BEN",
        "numeric": "204",
        "dialing": "+229",
        "capital": "Porto-Novo",
        "region": "Africa"
    },
    {
        "name": "Bhutan",
        "iso2": "BT",
        "iso3": "BTN",
        "numeric": "064",
        "dialing": "+975",
        "capital": "Thimphu",
        "region": "Asia"
    },
    {
        "name": "Bolivia",
        "iso2": "BO",
        "iso3": "BOL",
        "numeric": "068",
        "dialing": "+591",
        "capital": "Sucre",
        "region": "South America"
    },
    {
        "name": "Bosnia and Herzegovina",
        "iso2": "BA",
        "iso3": "BIH",
        "numeric": "070",
        "dialing": "+387",
        "capital": "Sarajevo",
        "region": "Europe"
    },
    {
        "name": "Botswana",
        "iso2": "BW",
        "iso3": "BWA",
        "numeric": "072",
        "dialing": "+267",
        "capital": "Gaborone",
        "region": "Africa"
    },
    {
        "name": "Brazil",
        "iso2": "BR",
        "iso3": "BRA",
        "numeric": "076",
        "dialing": "+55",
        "capital": "Brasília",
        "region": "South America"
    },
    {
        "name": "Brunei",
        "iso2": "BN",
        "iso3": "BRN",
        "numeric": "096",
        "dialing": "+673",
        "capital": "Bandar Seri Begawan",
        "region": "Asia"
    },
    {
        "name": "Bulgaria",
        "iso2": "BG",
        "iso3": "BGR",
        "numeric": "100",
        "dialing": "+359",
        "capital": "Sofia",
        "region": "Europe"
    },
    {
        "name": "Burkina Faso",
        "iso2": "BF",
        "iso3": "BFA",
        "numeric": "854",
        "dialing": "+226",
        "capital": "Ouagadougou",
        "region": "Africa"
    },
    {
        "name": "Burundi",
        "iso2": "BI",
        "iso3": "BDI",
        "numeric": "108",
        "dialing": "+257",
        "capital": "Gitega",
        "region": "Africa"
    },
    {
        "name": "Cabo Verde",
        "iso2": "CV",
        "iso3": "CPV",
        "numeric": "132",
        "dialing": "+238",
        "capital": "Praia",
        "region": "Africa"
    },
    {
        "name": "Cambodia",
        "iso2": "KH",
        "iso3": "KHM",
        "numeric": "116",
        "dialing": "+855",
        "capital": "Phnom Penh",
        "region": "Asia"
    },
    {
        "name": "Cameroon",
        "iso2": "CM",
        "iso3": "CMR",
        "numeric": "120",
        "dialing": "+237",
        "capital": "Yaoundé",
        "region": "Africa"
    },
    {
        "name": "Canada",
        "iso2": "CA",
        "iso3": "CAN",
        "numeric": "124",
        "dialing": "+1",
        "capital": "Ottawa",
        "region": "North America"
    },
    {
        "name": "Central African Republic",
        "iso2": "CF",
        "iso3": "CAF",
        "numeric": "140",
        "dialing": "+236",
        "capital": "Bangui",
        "region": "Africa"
    },
    {
        "name": "Chad",
        "iso2": "TD",
        "iso3": "TCD",
        "numeric": "148",
        "dialing": "+235",
        "capital": "N'Djamena",
        "region": "Africa"
    },
    {
        "name": "Chile",
        "iso2": "CL",
        "iso3": "CHL",
        "numeric": "152",
        "dialing": "+56",
        "capital": "Santiago",
        "region": "South America"
    },
    {
        "name": "China",
        "iso2": "CN",
        "iso3": "CHN",
        "numeric": "156",
        "dialing": "+86",
        "capital": "Beijing",
        "region": "Asia"
    },
    {
        "name": "Colombia",
        "iso2": "CO",
        "iso3": "COL",
        "numeric": "170",
        "dialing": "+57",
        "capital": "Bogotá",
        "region": "South America"
    },
    {
        "name": "Comoros",
        "iso2": "KM",
        "iso3": "COM",
        "numeric": "174",
        "dialing": "+269",
        "capital": "Moroni",
        "region": "Africa"
    },
    {
        "name": "Congo (Republic of the)",
        "iso2": "CG",
        "iso3": "COG",
        "numeric": "178",
        "dialing": "+242",
        "capital": "Brazzaville",
        "region": "Africa"
    },
    {
        "name": "Congo (Democratic Republic of the)",
        "iso2": "CD",
        "iso3": "COD",
        "numeric": "180",
        "dialing": "+243",
        "capital": "Kinshasa",
        "region": "Africa"
    },
    {
        "name": "Costa Rica",
        "iso2": "CR",
        "iso3": "CRI",
        "numeric": "188",
        "dialing": "+506",
        "capital": "San José",
        "region": "North America"
    },
    {
        "name": "Côte d'Ivoire",
        "iso2": "CI",
        "iso3": "CIV",
        "numeric": "384",
        "dialing": "+225",
        "capital": "Yamoussoukro",
        "region": "Africa"
    },
    {
        "name": "Croatia",
        "iso2": "HR",
        "iso3": "HRV",
        "numeric": "191",
        "dialing": "+385",
        "capital": "Zagreb",
        "region": "Europe"
    },
    {
        "name": "Cuba",
        "iso2": "CU",
        "iso3": "CUB",
        "numeric": "192",
        "dialing": "+53",
        "capital": "Havana",
        "region": "North America"
    },
    {
        "name": "Cyprus",
        "iso2": "CY",
        "iso3": "CYP",
        "numeric": "196",
        "dialing": "+357",
        "capital": "Nicosia",
        "region": "Asia"
    },
    {
        "name": "Czechia",
        "iso2": "CZ",
        "iso3": "CZE",
        "numeric": "203",
        "dialing": "+420",
        "capital": "Prague",
        "region": "Europe"
    },
    {
        "name": "Denmark",
        "iso2": "DK",
        "iso3": "DNK",
        "numeric": "208",
        "dialing": "+45",
        "capital": "Copenhagen",
        "region": "Europe"
    },
    {
        "name": "Djibouti",
        "iso2": "DJ",
        "iso3": "DJI",
        "numeric": "262",
        "dialing": "+253",
        "capital": "Djibouti",
        "region": "Africa"
    },
    {
        "name": "Dominica",
        "iso2": "DM",
        "iso3": "DMA",
        "numeric": "212",
        "dialing": "+1",
        "capital": "Roseau",
        "region": "North America"
    },
    {
        "name": "Dominican Republic",
        "iso2": "DO",
        "iso3": "DOM",
        "numeric": "214",
        "dialing": "+1",
        "capital": "Santo Domingo",
        "region": "North America"
    },
    {
        "name": "Ecuador",
        "iso2": "EC",
        "iso3": "ECU",
        "numeric": "218",
        "dialing": "+593",
        "capital": "Quito",
        "region": "South America"
    },
    {
        "name": "Egypt",
        "iso2": "EG",
        "iso3": "EGY",
        "numeric": "818",
        "dialing": "+20",
        "capital": "Cairo",
        "region": "Africa"
    },
    {
        "name": "El Salvador",
        "iso2": "SV",
        "iso3": "SLV",
        "numeric": "222",
        "dialing": "+503",
        "capital": "San Salvador",
        "region": "North America"
    },
    {
        "name": "Equatorial Guinea",
        "iso2": "GQ",
        "iso3": "GNQ",
        "numeric": "226",
        "dialing": "+240",
        "capital": "Malabo",
        "region": "Africa"
    },
    {
        "name": "Eritrea",
        "iso2": "ER",
        "iso3": "ERI",
        "numeric": "232",
        "dialing": "+291",
        "capital": "Asmara",
        "region": "Africa"
    },
    {
        "name": "Estonia",
        "iso2": "EE",
        "iso3": "EST",
        "numeric": "233",
        "dialing": "+372",
        "capital": "Tallinn",
        "region": "Europe"
    },
    {
        "name": "Eswatini",
        "iso2": "SZ",
        "iso3": "SWZ",
        "numeric": "748",
        "dialing": "+268",
        "capital": "Mbabane",
        "region": "Africa"
    },
    {
        "name": "Ethiopia",
        "iso2": "ET",
        "iso3": "ETH",
        "numeric": "231",
        "dialing": "+251",
        "capital": "Addis Ababa",
        "region": "Africa"
    },
    {
        "name": "Fiji",
        "iso2": "FJ",
        "iso3": "FJI",
        "numeric": "242",
        "dialing": "+679",
        "capital": "Suva",
        "region": "Oceania"
    },
    {
        "name": "Finland",
        "iso2": "FI",
        "iso3": "FIN",
        "numeric": "246",
        "dialing": "+358",
        "capital": "Helsinki",
        "region": "Europe"
    },
    {
        "name": "France",
        "iso2": "FR",
        "iso3": "FRA",
        "numeric": "250",
        "dialing": "+33",
        "capital": "Paris",
        "region": "Europe"
    },
    {
        "name": "Gabon",
        "iso2": "GA",
        "iso3": "GAB",
        "numeric": "266",
        "dialing": "+241",
        "capital": "Libreville",
        "region": "Africa"
    },
    {
        "name": "Gambia",
        "iso2": "GM",
        "iso3": "GMB",
        "numeric": "270",
        "dialing": "+220",
        "capital": "Banjul",
        "region": "Africa"
    },
    {
        "name": "Georgia",
        "iso2": "GE",
        "iso3": "GEO",
        "numeric": "268",
        "dialing": "+995",
        "capital": "Tbilisi",
        "region": "Asia"
    },
    {
        "name": "Germany",
        "iso2": "DE",
        "iso3": "DEU",
        "numeric": "276",
        "dialing": "+49",
        "capital": "Berlin",
        "region": "Europe"
    },
    {
        "name": "Ghana",
        "iso2": "GH",
        "iso3": "GHA",
        "numeric": "288",
        "dialing": "+233",
        "capital": "Accra",
        "region": "Africa"
    },
    {
        "name": "Greece",
        "iso2": "GR",
        "iso3": "GRC",
        "numeric": "300",
        "dialing": "+30",
        "capital": "Athens",
        "region": "Europe"
    },
    {
        "name": "Grenada",
        "iso2": "GD",
        "iso3": "GRD",
        "numeric": "308",
        "dialing": "+1",
        "capital": "Saint George's",
        "region": "North America"
    },
    {
        "name": "Guatemala",
        "iso2": "GT",
        "iso3": "GTM",
        "numeric": "320",
        "dialing": "+502",
        "capital": "Guatemala City",
        "region": "North America"
    },
    {
        "name": "Guinea",
        "iso2": "GN",
        "iso3": "GIN",
        "numeric": "324",
        "dialing": "+224",
        "capital": "Conakry",
        "region": "Africa"
    },
    {
        "name": "Guinea-Bissau",
        "iso2": "GW",
        "iso3": "GNB",
        "numeric": "624",
        "dialing": "+245",
        "capital": "Bissau",
        "region": "Africa"
    },
    {
        "name": "Guyana",
        "iso2": "GY",
        "iso3": "GUY",
        "numeric": "328",
        "dialing": "+592",
        "capital": "Georgetown",
        "region": "South America"
    },
    {
        "name": "Haiti",
        "iso2": "HT",
        "iso3": "HTI",
        "numeric": "332",
        "dialing": "+509",
        "capital": "Port-au-Prince",
        "region": "North America"
    },
    {
        "name": "Honduras",
        "iso2": "HN",
        "iso3": "HND",
        "numeric": "340",
        "dialing": "+504",
        "capital": "Tegucigalpa",
        "region": "North America"
    },
    {
        "name": "Hungary",
        "iso2": "HU",
        "iso3": "HUN",
        "numeric": "348",
        "dialing": "+36",
        "capital": "Budapest",
        "region": "Europe"
    },
    {
        "name": "Iceland",
        "iso2": "IS",
        "iso3": "ISL",
        "numeric": "352",
        "dialing": "+354",
        "capital": "Reykjavík",
        "region": "Europe"
    },
    {
        "name": "India",
        "iso2": "IN",
        "iso3": "IND",
        "numeric": "356",
        "dialing": "+91",
        "capital": "New Delhi",
        "region": "Asia"
    },
    {
        "name": "Indonesia",
        "iso2": "ID",
        "iso3": "IDN",
        "numeric": "360",
        "dialing": "+62",
        "capital": "Jakarta",
        "region": "Asia"
    },
    {
        "name": "Iran",
        "iso2": "IR",
        "iso3": "IRN",
        "numeric": "364",
        "dialing": "+98",
        "capital": "Tehran",
        "region": "Asia"
    },
    {
        "name": "Iraq",
        "iso2": "IQ",
        "iso3": "IRQ",
        "numeric": "368",
        "dialing": "+964",
        "capital": "Baghdad",
        "region": "Asia"
    },
    {
        "name": "Ireland",
        "iso2": "IE",
        "iso3": "IRL",
        "numeric": "372",
        "dialing": "+353",
        "capital": "Dublin",
        "region": "Europe"
    },
    {
        "name": "Israel",
        "iso2": "IL",
        "iso3": "ISR",
        "numeric": "376",
        "dialing": "+972",
        "capital": "Jerusalem",
        "region": "Asia"
    },
    {
        "name": "Italy",
        "iso2": "IT",
        "iso3": "ITA",
        "numeric": "380",
        "dialing": "+39",
        "capital": "Rome",
        "region": "Europe"
    },
    {
        "name": "Jamaica",
        "iso2": "JM",
        "iso3": "JAM",
        "numeric": "388",
        "dialing": "+1",
        "capital": "Kingston",
        "region": "North America"
    },
    {
        "name": "Japan",
        "iso2": "JP",
        "iso3": "JPN",
        "numeric": "392",
        "dialing": "+81",
        "capital": "Tokyo",
        "region": "Asia"
    },
    {
        "name": "Jordan",
        "iso2": "JO",
        "iso3": "JOR",
        "numeric": "400",
        "dialing": "+962",
        "capital": "Amman",
        "region": "Asia"
    },
    {
        "name": "Kazakhstan",
        "iso2": "KZ",
        "iso3": "KAZ",
        "numeric": "398",
        "dialing": "+7",
        "capital": "Astana",
        "region": "Asia"
    },
    {
        "name": "Kenya",
        "iso2": "KE",
        "iso3": "KEN",
        "numeric": "404",
        "dialing": "+254",
        "capital": "Nairobi",
        "region": "Africa"
    },
    {
        "name": "Kiribati",
        "iso2": "KI",
        "iso3": "KIR",
        "numeric": "296",
        "dialing": "+686",
        "capital": "Tarawa",
        "region": "Oceania"
    },
    {
        "name": "Korea (North)",
        "iso2": "KP",
        "iso3": "PRK",
        "numeric": "408",
        "dialing": "+850",
        "capital": "Pyongyang",
        "region": "Asia"
    },
    {
        "name": "Korea (South)",
        "iso2": "KR",
        "iso3": "KOR",
        "numeric": "410",
        "dialing": "+82",
        "capital": "Seoul",
        "region": "Asia"
    },
    {
        "name": "Kuwait",
        "iso2": "KW",
        "iso3": "KWT",
        "numeric": "414",
        "dialing": "+965",
        "capital": "Kuwait City",
        "region": "Asia"
    },
    {
        "name": "Kyrgyzstan",
        "iso2": "KG",
        "iso3": "KGZ",
        "numeric": "417",
        "dialing": "+996",
        "capital": "Bishkek",
        "region": "Asia"
    },
    {
        "name": "Laos",
        "iso2": "LA",
        "iso3": "LAO",
        "numeric": "418",
        "dialing": "+856",
        "capital": "Vientiane",
        "region": "Asia"
    },
    {
        "name": "Latvia",
        "iso2": "LV",
        "iso3": "LVA",
        "numeric": "428",
        "dialing": "+371",
        "capital": "Riga",
        "region": "Europe"
    },
    {
        "name": "Lebanon",
        "iso2": "LB",
        "iso3": "LBN",
        "numeric": "422",
        "dialing": "+961",
        "capital": "Beirut",
        "region": "Asia"
    },
    {
        "name": "Lesotho",
        "iso2": "LS",
        "iso3": "LSO",
        "numeric": "426",
        "dialing": "+266",
        "capital": "Maseru",
        "region": "Africa"
    },
    {
        "name": "Liberia",
        "iso2": "LR",
        "iso3": "LBR",
        "numeric": "430",
        "dialing": "+231",
        "capital": "Monrovia",
        "region": "Africa"
    },
    {
        "name": "Libya",
        "iso2": "LY",
        "iso3": "LBY",
        "numeric": "434",
        "dialing": "+218",
        "capital": "Tripoli",
        "region": "Africa"
    },
    {
        "name": "Liechtenstein",
        "iso2": "LI",
        "iso3": "LIE",
        "numeric": "438",
        "dialing": "+423",
        "capital": "Vaduz",
        "region": "Europe"
    },
    {
        "name": "Lithuania",
        "iso2": "LT",
        "iso3": "LTU",
        "numeric": "440",
        "dialing": "+370",
        "capital": "Vilnius",
        "region": "Europe"
    },
    {
        "name": "Luxembourg",
        "iso2": "LU",
        "iso3": "LUX",
        "numeric": "442",
        "dialing": "+352",
        "capital": "Luxembourg",
        "region": "Europe"
    },
    {
        "name": "Madagascar",
        "iso2": "MG",
        "iso3": "MDG",
        "numeric": "450",
        "dialing": "+261",
        "capital": "Antananarivo",
        "region": "Africa"
    },
    {
        "name": "Malawi",
        "iso2": "MW",
        "iso3": "MWI",
        "numeric": "454",
        "dialing": "+265",
        "capital": "Lilongwe",
        "region": "Africa"
    },
    {
        "name": "Malaysia",
        "iso2": "MY",
        "iso3": "MYS",
        "numeric": "458",
        "dialing": "+60",
        "capital": "Kuala Lumpur",
        "region": "Asia"
    },
    {
        "name": "Maldives",
        "iso2": "MV",
        "iso3": "MDV",
        "numeric": "462",
        "dialing": "+960",
        "capital": "Malé",
        "region": "Asia"
    },
    {
        "name": "Mali",
        "iso2": "ML",
        "iso3": "MLI",
        "numeric": "466",
        "dialing": "+223",
        "capital": "Bamako",
        "region": "Africa"
    },
    {
        "name": "Malta",
        "iso2": "MT",
        "iso3": "MLT",
        "numeric": "470",
        "dialing": "+356",
        "capital": "Valletta",
        "region": "Europe"
    },
    {
        "name": "Marshall Islands",
        "iso2": "MH",
        "iso3": "MHL",
        "numeric": "584",
        "dialing": "+692",
        "capital": "Majuro",
        "region": "Oceania"
    },
    {
        "name": "Mauritania",
        "iso2": "MR",
        "iso3": "MRT",
        "numeric": "478",
        "dialing": "+222",
        "capital": "Nouakchott",
        "region": "Africa"
    },
    {
        "name": "Mauritius",
        "iso2": "MU",
        "iso3": "MUS",
        "numeric": "480",
        "dialing": "+230",
        "capital": "Port Louis",
        "region": "Africa"
    },
    {
        "name": "Mexico",
        "iso2": "MX",
        "iso3": "MEX",
        "numeric": "484",
        "dialing": "+52",
        "capital": "Mexico City",
        "region": "North America"
    },
    {
        "name": "Micronesia",
        "iso2": "FM",
        "iso3": "FSM",
        "numeric": "583",
        "dialing": "+691",
        "capital": "Palikir",
        "region": "Oceania"
    },
    {
        "name": "Moldova",
        "iso2": "MD",
        "iso3": "MDA",
        "numeric": "498",
        "dialing": "+373",
        "capital": "Chișinău",
        "region": "Europe"
    },
    {
        "name": "Monaco",
        "iso2": "MC",
        "iso3": "MCO",
        "numeric": "492",
        "dialing": "+377",
        "capital": "Monaco",
        "region": "Europe"
    },
    {
        "name": "Mongolia",
        "iso2": "MN",
        "iso3": "MNG",
        "numeric": "496",
        "dialing": "+976",
        "capital": "Ulaanbaatar",
        "region": "Asia"
    },
    {
        "name": "Montenegro",
        "iso2": "ME",
        "iso3": "MNE",
        "numeric": "499",
        "dialing": "+382",
        "capital": "Podgorica",
        "region": "Europe"
    },
    {
        "name": "Morocco",
        "iso2": "MA",
        "iso3": "MAR",
        "numeric": "504",
        "dialing": "+212",
        "capital": "Rabat",
        "region": "Africa"
    },
    {
        "name": "Mozambique",
        "iso2": "MZ",
        "iso3": "MOZ",
        "numeric": "508",
        "dialing": "+258",
        "capital": "Maputo",
        "region": "Africa"
    },
    {
        "name": "Myanmar",
        "iso2": "MM",
        "iso3": "MMR",
        "numeric": "104",
        "dialing": "+95",
        "capital": "Naypyidaw",
        "region": "Asia"
    },
    {
        "name": "Namibia",
        "iso2": "NA",
        "iso3": "NAM",
        "numeric": "516",
        "dialing": "+264",
        "capital": "Windhoek",
        "region": "Africa"
    },
    {
        "name": "Nauru",
        "iso2": "NR",
        "iso3": "NRU",
        "numeric": "520",
        "dialing": "+674",
        "capital": "Yaren",
        "region": "Oceania"
    },
    {
        "name": "Nepal",
        "iso2": "NP",
        "iso3": "NPL",
        "numeric": "524",
        "dialing": "+977",
        "capital": "Kathmandu",
        "region": "Asia"
    },
    {
        "name": "Netherlands",
        "iso2": "NL",
        "iso3": "NLD",
        "numeric": "528",
        "dialing": "+31",
        "capital": "Amsterdam",
        "region": "Europe"
    },
    {
        "name": "New Zealand",
        "iso2": "NZ",
        "iso3": "NZL",
        "numeric": "554",
        "dialing": "+64",
        "capital": "Wellington",
        "region": "Oceania"
    },
    {
        "name": "Nicaragua",
        "iso2": "NI",
        "iso3": "NIC",
        "numeric": "558",
        "dialing": "+505",
        "capital": "Managua",
        "region": "North America"
    },
    {
        "name": "Niger",
        "iso2": "NE",
        "iso3": "NER",
        "numeric": "562",
        "dialing": "+227",
        "capital": "Niamey",
        "region": "Africa"
    },
    {
        "name": "Nigeria",
        "iso2": "NG",
        "iso3": "NGA",
        "numeric": "566",
        "dialing": "+234",
        "capital": "Abuja",
        "region": "Africa"
    },
    {
        "name": "North Macedonia",
        "iso2": "MK",
        "iso3": "MKD",
        "numeric": "807",
        "dialing": "+389",
        "capital": "Skopje",
        "region": "Europe"
    },
    {
        "name": "Norway",
        "iso2": "NO",
        "iso3": "NOR",
        "numeric": "578",
        "dialing": "+47",
        "capital": "Oslo",
        "region": "Europe"
    },
    {
        "name": "Oman",
        "iso2": "OM",
        "iso3": "OMN",
        "numeric": "512",
        "dialing": "+968",
        "capital": "Muscat",
        "region": "Asia"
    },
    {
        "name": "Pakistan",
        "iso2": "PK",
        "iso3": "PAK",
        "numeric": "586",
        "dialing": "+92",
        "capital": "Islamabad",
        "region": "Asia"
    },
    {
        "name": "Palau",
        "iso2": "PW",
        "iso3": "PLW",
        "numeric": "585",
        "dialing": "+680",
        "capital": "Ngerulmud",
        "region": "Oceania"
    },
    {
        "name": "Palestine",
        "iso2": "PS",
        "iso3": "PSE",
        "numeric": "275",
        "dialing": "+970",
        "capital": "Ramallah",
        "region": "Asia"
    },
    {
        "name": "Panama",
        "iso2": "PA",
        "iso3": "PAN",
        "numeric": "591",
        "dialing": "+507",
        "capital": "Panama City",
        "region": "North America"
    },
    {
        "name": "Papua New Guinea",
        "iso2": "PG",
        "iso3": "PNG",
        "numeric": "598",
        "dialing": "+675",
        "capital": "Port Moresby",
        "region": "Oceania"
    },
    {
        "name": "Paraguay",
        "iso2": "PY",
        "iso3": "PRY",
        "numeric": "600",
        "dialing": "+595",
        "capital": "Asunción",
        "region": "South America"
    },
    {
        "name": "Peru",
        "iso2": "PE",
        "iso3": "PER",
        "numeric": "604",
        "dialing": "+51",
        "capital": "Lima",
        "region": "South America"
    },
    {
        "name": "Philippines",
        "iso2": "PH",
        "iso3": "PHL",
        "numeric": "608",
        "dialing": "+63",
        "capital": "Manila",
        "region": "Asia"
    },
    {
        "name": "Poland",
        "iso2": "PL",
        "iso3": "POL",
        "numeric": "616",
        "dialing": "+48",
        "capital": "Warsaw",
        "region": "Europe"
    },
    {
        "name": "Portugal",
        "iso2": "PT",
        "iso3": "PRT",
        "numeric": "620",
        "dialing": "+351",
        "capital": "Lisbon",
        "region": "Europe"
    },
    {
        "name": "Qatar",
        "iso2": "QA",
        "iso3": "QAT",
        "numeric": "634",
        "dialing": "+974",
        "capital": "Doha",
        "region": "Asia"
    },
    {
        "name": "Romania",
        "iso2": "RO",
        "iso3": "ROU",
        "numeric": "642",
        "dialing": "+40",
        "capital": "Bucharest",
        "region": "Europe"
    },
    {
        "name": "Russia",
        "iso2": "RU",
        "iso3": "RUS",
        "numeric": "643",
        "dialing": "+7",
        "capital": "Moscow",
        "region": "Europe"
    },
    {
        "name": "Rwanda",
        "iso2": "RW",
        "iso3": "RWA",
        "numeric": "646",
        "dialing": "+250",
        "capital": "Kigali",
        "region": "Africa"
    },
    {
        "name": "Saint Kitts and Nevis",
        "iso2": "KN",
        "iso3": "KNA",
        "numeric": "659",
        "dialing": "+1",
        "capital": "Basseterre",
        "region": "North America"
    },
    {
        "name": "Saint Lucia",
        "iso2": "LC",
        "iso3": "LCA",
        "numeric": "662",
        "dialing": "+1",
        "capital": "Castries",
        "region": "North America"
    },
    {
        "name": "Saint Vincent and the Grenadines",
        "iso2": "VC",
        "iso3": "VCT",
        "numeric": "670",
        "dialing": "+1",
        "capital": "Kingstown",
        "region": "North America"
    },
    {
        "name": "Samoa",
        "iso2": "WS",
        "iso3": "WSM",
        "numeric": "882",
        "dialing": "+685",
        "capital": "Apia",
        "region": "Oceania"
    },
    {
        "name": "San Marino",
        "iso2": "SM",
        "iso3": "SMR",
        "numeric": "674",
        "dialing": "+378",
        "capital": "San Marino",
        "region": "Europe"
    },
    {
        "name": "Sao Tome and Principe",
        "iso2": "ST",
        "iso3": "STP",
        "numeric": "678",
        "dialing": "+239",
        "capital": "São Tomé",
        "region": "Africa"
    },
    {
        "name": "Saudi Arabia",
        "iso2": "SA",
        "iso3": "SAU",
        "numeric": "682",
        "dialing": "+966",
        "capital": "Riyadh",
        "region": "Asia"
    },
    {
        "name": "Senegal",
        "iso2": "SN",
        "iso3": "SEN",
        "numeric": "686",
        "dialing": "+221",
        "capital": "Dakar",
        "region": "Africa"
    },
    {
        "name": "Serbia",
        "iso2": "RS",
        "iso3": "SRB",
        "numeric": "688",
        "dialing": "+381",
        "capital": "Belgrade",
        "region": "Europe"
    },
    {
        "name": "Seychelles",
        "iso2": "SC",
        "iso3": "SYC",
        "numeric": "690",
        "dialing": "+248",
        "capital": "Victoria",
        "region": "Africa"
    },
    {
        "name": "Sierra Leone",
        "iso2": "SL",
        "iso3": "SLE",
        "numeric": "694",
        "dialing": "+232",
        "capital": "Freetown",
        "region": "Africa"
    },
    {
        "name": "Singapore",
        "iso2": "SG",
        "iso3": "SGP",
        "numeric": "702",
        "dialing": "+65",
        "capital": "Singapore",
        "region": "Asia"
    },
    {
        "name": "Slovakia",
        "iso2": "SK",
        "iso3": "SVK",
        "numeric": "703",
        "dialing": "+421",
        "capital": "Bratislava",
        "region": "Europe"
    },
    {
        "name": "Slovenia",
        "iso2": "SI",
        "iso3": "SVN",
        "numeric": "705",
        "dialing": "+386",
        "capital": "Ljubljana",
        "region": "Europe"
    },
    {
        "name": "Solomon Islands",
        "iso2": "SB",
        "iso3": "SLB",
        "numeric": "090",
        "dialing": "+677",
        "capital": "Honiara",
        "region": "Oceania"
    },
    {
        "name": "Somalia",
        "iso2": "SO",
        "iso3": "SOM",
        "numeric": "706",
        "dialing": "+252",
        "capital": "Mogadishu",
        "region": "Africa"
    },
    {
        "name": "South Africa",
        "iso2": "ZA",
        "iso3": "ZAF",
        "numeric": "710",
        "dialing": "+27",
        "capital": "Pretoria",
        "region": "Africa"
    },
    {
        "name": "South Sudan",
        "iso2": "SS",
        "iso3": "SSD",
        "numeric": "728",
        "dialing": "+211",
        "capital": "Juba",
        "region": "Africa"
    },
    {
        "name": "Spain",
        "iso2": "ES",
        "iso3": "ESP",
        "numeric": "724",
        "dialing": "+34",
        "capital": "Madrid",
        "region": "Europe"
    },
    {
        "name": "Sri Lanka",
        "iso2": "LK",
        "iso3": "LKA",
        "numeric": "144",
        "dialing": "+94",
        "capital": "Sri Jayawardenepura Kotte",
        "region": "Asia"
    },
    {
        "name": "Sudan",
        "iso2": "SD",
        "iso3": "SDN",
        "numeric": "729",
        "dialing": "+249",
        "capital": "Khartoum",
        "region": "Africa"
    },
    {
        "name": "Suriname",
        "iso2": "SR",
        "iso3": "SUR",
        "numeric": "740",
        "dialing": "+597",
        "capital": "Paramaribo",
        "region": "South America"
    },
    {
        "name": "Sweden",
        "iso2": "SE",
        "iso3": "SWE",
        "numeric": "752",
        "dialing": "+46",
        "capital": "Stockholm",
        "region": "Europe"
    },
    {
        "name": "Switzerland",
        "iso2": "CH",
        "iso3": "CHE",
        "numeric": "756",
        "dialing": "+41",
        "capital": "Bern",
        "region": "Europe"
    },
    {
        "name": "Syria",
        "iso2": "SY",
        "iso3": "SYR",
        "numeric": "760",
        "dialing": "+963",
        "capital": "Damascus",
        "region": "Asia"
    },
    {
        "name": "Taiwan",
        "iso2": "TW",
        "iso3": "TWN",
        "numeric": "158",
        "dialing": "+886",
        "capital": "Taipei",
        "region": "Asia"
    },
    {
        "name": "Tajikistan",
        "iso2": "TJ",
        "iso3": "TJK",
        "numeric": "762",
        "dialing": "+992",
        "capital": "Dushanbe",
        "region": "Asia"
    },
    {
        "name": "Tanzania",
        "iso2": "TZ",
        "iso3": "TZA",
        "numeric": "834",
        "dialing": "+255",
        "capital": "Dodoma",
        "region": "Africa"
    },
    {
        "name": "Thailand",
        "iso2": "TH",
        "iso3": "THA",
        "numeric": "764",
        "dialing": "+66",
        "capital": "Bangkok",
        "region": "Asia"
    },
    {
        "name": "Timor-Leste",
        "iso2": "TL",
        "iso3": "TLS",
        "numeric": "626",
        "dialing": "+670",
        "capital": "Dili",
        "region": "Asia"
    },
    {
        "name": "Togo",
        "iso2": "TG",
        "iso3": "TGO",
        "numeric": "768",
        "dialing": "+228",
        "capital": "Lomé",
        "region": "Africa"
    },
    {
        "name": "Tonga",
        "iso2": "TO",
        "iso3": "TON",
        "numeric": "776",
        "dialing": "+676",
        "capital": "Nuku'alofa",
        "region": "Oceania"
    },
    {
        "name": "Trinidad and Tobago",
        "iso2": "TT",
        "iso3": "TTO",
        "numeric": "780",
        "dialing": "+1",
        "capital": "Port of Spain",
        "region": "North America"
    },
    {
        "name": "Tunisia",
        "iso2": "TN",
        "iso3": "TUN",
        "numeric": "788",
        "dialing": "+216",
        "capital": "Tunis",
        "region": "Africa"
    },
    {
        "name": "Turkey",
        "iso2": "TR",
        "iso3": "TUR",
        "numeric": "792",
        "dialing": "+90",
        "capital": "Ankara",
        "region": "Asia"
    },
    {
        "name": "Turkmenistan",
        "iso2": "TM",
        "iso3": "TKM",
        "numeric": "795",
        "dialing": "+993",
        "capital": "Ashgabat",
        "region": "Asia"
    },
    {
        "name": "Tuvalu",
        "iso2": "TV",
        "iso3": "TUV",
        "numeric": "798",
        "dialing": "+688",
        "capital": "Funafuti",
        "region": "Oceania"
    },
    {
        "name": "Uganda",
        "iso2": "UG",
        "iso3": "UGA",
        "numeric": "800",
        "dialing": "+256",
        "capital": "Kampala",
        "region": "Africa"
    },
    {
        "name": "Ukraine",
        "iso2": "UA",
        "iso3": "UKR",
        "numeric": "804",
        "dialing": "+380",
        "capital": "Kyiv",
        "region": "Europe"
    },
    {
        "name": "United Arab Emirates",
        "iso2": "AE",
        "iso3": "ARE",
        "numeric": "784",
        "dialing": "+971",
        "capital": "Abu Dhabi",
        "region": "Asia"
    },
    {
        "name": "United Kingdom",
        "iso2": "GB",
        "iso3": "GBR",
        "numeric": "826",
        "dialing": "+44",
        "capital": "London",
        "region": "Europe"
    },
    {
        "name": "United States",
        "iso2": "US",
        "iso3": "USA",
        "numeric": "840",
        "dialing": "+1",
        "capital": "Washington, D.C.",
        "region": "North America"
    },
    {
        "name": "Uruguay",
        "iso2": "UY",
        "iso3": "URY",
        "numeric": "858",
        "dialing": "+598",
        "capital": "Montevideo",
        "region": "South America"
    },
    {
        "name": "Uzbekistan",
        "iso2": "UZ",
        "iso3": "UZB",
        "numeric": "860",
        "dialing": "+998",
        "capital": "Tashkent",
        "region": "Asia"
    },
    {
        "name": "Vanuatu",
        "iso2": "VU",
        "iso3": "VUT",
        "numeric": "548",
        "dialing": "+678",
        "capital": "Port Vila",
        "region": "Oceania"
    },
    {
        "name": "Vatican City",
        "iso2": "VA",
        "iso3": "VAT",
        "numeric": "336",
        "dialing": "+39",
        "capital": "Vatican City",
        "region": "Europe"
    },
    {
        "name": "Venezuela",
        "iso2": "VE",
        "iso3": "VEN",
        "numeric": "862",
        "dialing": "+58",
        "capital": "Caracas",
        "region": "South America"
    },
    {
        "name": "Vietnam",
        "iso2": "VN",
        "iso3": "VNM",
        "numeric": "704",
        "dialing": "+84",
        "capital": "Hanoi",
        "region": "Asia"
    },
    {
        "name": "Yemen",
        "iso2": "YE",
        "iso3": "YEM",
        "numeric": "887",
        "dialing": "+967",
        "capital": "Sana'a",
        "region": "Asia"
    },
    {
        "name": "Zambia",
        "iso2": "ZM",
        "iso3": "ZMB",
        "numeric": "894",
        "dialing": "+260",
        "capital": "Lusaka",
        "region": "Africa"
    },
    {
        "name": "Zimbabwe",
        "iso2": "ZW",
        "iso3": "ZWE",
        "numeric": "716",
        "dialing": "+263",
        "capital": "Harare",
        "region": "Africa"
    },
    {
        "name": "Kosovo",
        "iso2": "XK",
        "iso3": "XKX",
        "numeric": "926",
        "dialing": "+383",
        "capital": "Pristina",
        "region": "Europe"
    },
    {
        "name": "Hong Kong",
        "iso2": "HK",
        "iso3": "HKG",
        "numeric": "344",
        "dialing": "+852",
        "capital": "Hong Kong",
        "region": "Asia"
    },
    {
        "name": "Macau",
        "iso2": "MO",
        "iso3": "MAC",
        "numeric": "446",
        "dialing": "+853",
        "capital": "Macau",
        "region": "Asia"
    },
    {
        "name": "Puerto Rico",
        "iso2": "PR",
        "iso3": "PRI",
        "numeric": "630",
        "dialing": "+1",
        "capital": "San Juan",
        "region": "North America"
    },
    {
        "name": "Greenland",
        "iso2": "GL",
        "iso3": "GRL",
        "numeric": "304",
        "dialing": "+299",
        "capital": "Nuuk",
        "region": "North America"
    },
    {
        "name": "Faroe Islands",
        "iso2": "FO",
        "iso3": "FRO",
        "numeric": "234",
        "dialing": "+298",
        "capital": "Tórshavn",
        "region": "Europe"
    },
    {
        "name": "Gibraltar",
        "iso2": "GI",
        "iso3": "GIB",
        "numeric": "292",
        "dialing": "+350",
        "capital": "Gibraltar",
        "region": "Europe"
    },
    {
        "name": "Guam",
        "iso2": "GU",
        "iso3": "GUM",
        "numeric": "316",
        "dialing": "+1",
        "capital": "Hagåtña",
        "region": "Oceania"
    },
    {
        "name": "Bermuda",
        "iso2": "BM",
        "iso3": "BMU",
        "numeric": "060",
        "dialing": "+1",
        "capital": "Hamilton",
        "region": "North America"
    },
    {
        "name": "Cayman Islands",
        "iso2": "KY",
        "iso3": "CYM",
        "numeric": "136",
        "dialing": "+1",
        "capital": "George Town",
        "region": "North America"
    },
    {
        "name": "New Caledonia",
        "iso2": "NC",
        "iso3": "NCL",
        "numeric": "540",
        "dialing": "+687",
        "capital": "Nouméa",
        "region": "Oceania"
    },
    {
        "name": "French Polynesia",
        "iso2": "PF",
        "iso3": "PYF",
        "numeric": "258",
        "dialing": "+689",
        "capital": "Papeete",
        "region": "Oceania"
    },
    {
        "name": "Aruba",
        "iso2": "AW",
        "iso3": "ABW",
        "numeric": "533",
        "dialing": "+297",
        "capital": "Oranjestad",
        "region": "North America"
    },
    {
        "name": "Curaçao",
        "iso2": "CW",
        "iso3": "CUW",
        "numeric": "531",
        "dialing": "+599",
        "capital": "Willemstad",
        "region": "North America"
    },
    {
        "name": "Jersey",
        "iso2": "JE",
        "iso3": "JEY",
        "numeric": "832",
        "dialing": "+44",
        "capital": "Saint Helier",
        "region": "Europe"
    },
    {
        "name": "Guernsey",
        "iso2": "GG",
        "iso3": "GGY",
        "numeric": "831",
        "dialing": "+44",
        "capital": "Saint Peter Port",
        "region": "Europe"
    },
    {
        "name": "Isle of Man",
        "iso2": "IM",
        "iso3": "IMN",
        "numeric": "833",
        "dialing": "+44",
        "capital": "Douglas",
        "region": "Europe"
    },
    {
        "name": "American Samoa",
        "iso2": "AS",
        "iso3": "ASM",
        "numeric": "016",
        "dialing": "+1",
        "capital": "Pago Pago",
        "region": "Oceania"
    },
    {
        "name": "U.S. Virgin Islands",
        "iso2": "VI",
        "iso3": "VIR",
        "numeric": "850",
        "dialing": "+1",
        "capital": "Charlotte Amalie",
        "region": "North America"
    },
    {
        "name": "British Virgin Islands",
        "iso2": "VG",
        "iso3": "VGB",
        "numeric": "092",
        "dialing": "+1",
        "capital": "Road Town",
        "region": "North America"
    }
]

CURRENCIES = [
    {
        "code": "AED",
        "name": "UAE Dirham",
        "symbol": "د.إ",
        "numeric": "784",
        "used_in": "United Arab Emirates"
    },
    {
        "code": "AFN",
        "name": "Afghani",
        "symbol": "؋",
        "numeric": "971",
        "used_in": "Afghanistan"
    },
    {
        "code": "ALL",
        "name": "Lek",
        "symbol": "L",
        "numeric": "008",
        "used_in": "Albania"
    },
    {
        "code": "AMD",
        "name": "Armenian Dram",
        "symbol": "֏",
        "numeric": "051",
        "used_in": "Armenia"
    },
    {
        "code": "ANG",
        "name": "Netherlands Antillean Guilder",
        "symbol": "ƒ",
        "numeric": "532",
        "used_in": "Curaçao, Sint Maarten"
    },
    {
        "code": "AOA",
        "name": "Kwanza",
        "symbol": "Kz",
        "numeric": "973",
        "used_in": "Angola"
    },
    {
        "code": "ARS",
        "name": "Argentine Peso",
        "symbol": "$",
        "numeric": "032",
        "used_in": "Argentina"
    },
    {
        "code": "AUD",
        "name": "Australian Dollar",
        "symbol": "$",
        "numeric": "036",
        "used_in": "Australia"
    },
    {
        "code": "AWG",
        "name": "Aruban Florin",
        "symbol": "ƒ",
        "numeric": "533",
        "used_in": "Aruba"
    },
    {
        "code": "AZN",
        "name": "Azerbaijan Manat",
        "symbol": "₼",
        "numeric": "944",
        "used_in": "Azerbaijan"
    },
    {
        "code": "BAM",
        "name": "Convertible Mark",
        "symbol": "KM",
        "numeric": "977",
        "used_in": "Bosnia and Herzegovina"
    },
    {
        "code": "BBD",
        "name": "Barbados Dollar",
        "symbol": "$",
        "numeric": "052",
        "used_in": "Barbados"
    },
    {
        "code": "BDT",
        "name": "Taka",
        "symbol": "৳",
        "numeric": "050",
        "used_in": "Bangladesh"
    },
    {
        "code": "BGN",
        "name": "Bulgarian Lev",
        "symbol": "лв",
        "numeric": "975",
        "used_in": "Bulgaria"
    },
    {
        "code": "BHD",
        "name": "Bahraini Dinar",
        "symbol": ".د.ب",
        "numeric": "048",
        "used_in": "Bahrain"
    },
    {
        "code": "BIF",
        "name": "Burundi Franc",
        "symbol": "FBu",
        "numeric": "108",
        "used_in": "Burundi"
    },
    {
        "code": "BMD",
        "name": "Bermudian Dollar",
        "symbol": "$",
        "numeric": "060",
        "used_in": "Bermuda"
    },
    {
        "code": "BND",
        "name": "Brunei Dollar",
        "symbol": "$",
        "numeric": "096",
        "used_in": "Brunei"
    },
    {
        "code": "BOB",
        "name": "Boliviano",
        "symbol": "Bs.",
        "numeric": "068",
        "used_in": "Bolivia"
    },
    {
        "code": "BRL",
        "name": "Brazilian Real",
        "symbol": "R$",
        "numeric": "986",
        "used_in": "Brazil"
    },
    {
        "code": "BSD",
        "name": "Bahamian Dollar",
        "symbol": "$",
        "numeric": "044",
        "used_in": "Bahamas"
    },
    {
        "code": "BTN",
        "name": "Ngultrum",
        "symbol": "Nu.",
        "numeric": "064",
        "used_in": "Bhutan"
    },
    {
        "code": "BWP",
        "name": "Pula",
        "symbol": "P",
        "numeric": "072",
        "used_in": "Botswana"
    },
    {
        "code": "BYN",
        "name": "Belarusian Ruble",
        "symbol": "Br",
        "numeric": "933",
        "used_in": "Belarus"
    },
    {
        "code": "BZD",
        "name": "Belize Dollar",
        "symbol": "$",
        "numeric": "084",
        "used_in": "Belize"
    },
    {
        "code": "CAD",
        "name": "Canadian Dollar",
        "symbol": "$",
        "numeric": "124",
        "used_in": "Canada"
    },
    {
        "code": "CDF",
        "name": "Congolese Franc",
        "symbol": "FC",
        "numeric": "976",
        "used_in": "Democratic Republic of the Congo"
    },
    {
        "code": "CHF",
        "name": "Swiss Franc",
        "symbol": "Fr.",
        "numeric": "756",
        "used_in": "Switzerland, Liechtenstein"
    },
    {
        "code": "CLP",
        "name": "Chilean Peso",
        "symbol": "$",
        "numeric": "152",
        "used_in": "Chile"
    },
    {
        "code": "CNY",
        "name": "Yuan Renminbi",
        "symbol": "¥",
        "numeric": "156",
        "used_in": "China"
    },
    {
        "code": "COP",
        "name": "Colombian Peso",
        "symbol": "$",
        "numeric": "170",
        "used_in": "Colombia"
    },
    {
        "code": "CRC",
        "name": "Costa Rican Colon",
        "symbol": "₡",
        "numeric": "188",
        "used_in": "Costa Rica"
    },
    {
        "code": "CUP",
        "name": "Cuban Peso",
        "symbol": "$",
        "numeric": "192",
        "used_in": "Cuba"
    },
    {
        "code": "CVE",
        "name": "Cabo Verde Escudo",
        "symbol": "$",
        "numeric": "132",
        "used_in": "Cabo Verde"
    },
    {
        "code": "CZK",
        "name": "Czech Koruna",
        "symbol": "Kč",
        "numeric": "203",
        "used_in": "Czech Republic"
    },
    {
        "code": "DJF",
        "name": "Djibouti Franc",
        "symbol": "Fdj",
        "numeric": "262",
        "used_in": "Djibouti"
    },
    {
        "code": "DKK",
        "name": "Danish Krone",
        "symbol": "kr",
        "numeric": "208",
        "used_in": "Denmark"
    },
    {
        "code": "DOP",
        "name": "Dominican Peso",
        "symbol": "$",
        "numeric": "214",
        "used_in": "Dominican Republic"
    },
    {
        "code": "DZD",
        "name": "Algerian Dinar",
        "symbol": "دج",
        "numeric": "012",
        "used_in": "Algeria"
    },
    {
        "code": "EGP",
        "name": "Egyptian Pound",
        "symbol": "£",
        "numeric": "818",
        "used_in": "Egypt"
    },
    {
        "code": "ERN",
        "name": "Nakfa",
        "symbol": "Nfk",
        "numeric": "232",
        "used_in": "Eritrea"
    },
    {
        "code": "ETB",
        "name": "Ethiopian Birr",
        "symbol": "Br",
        "numeric": "230",
        "used_in": "Ethiopia"
    },
    {
        "code": "EUR",
        "name": "Euro",
        "symbol": "€",
        "numeric": "978",
        "used_in": "Eurozone"
    },
    {
        "code": "FJD",
        "name": "Fiji Dollar",
        "symbol": "$",
        "numeric": "242",
        "used_in": "Fiji"
    },
    {
        "code": "FKP",
        "name": "Falkland Islands Pound",
        "symbol": "£",
        "numeric": "238",
        "used_in": "Falkland Islands"
    },
    {
        "code": "GBP",
        "name": "Pound Sterling",
        "symbol": "£",
        "numeric": "826",
        "used_in": "United Kingdom"
    },
    {
        "code": "GEL",
        "name": "Lari",
        "symbol": "₾",
        "numeric": "981",
        "used_in": "Georgia"
    },
    {
        "code": "GHS",
        "name": "Ghana Cedi",
        "symbol": "₵",
        "numeric": "936",
        "used_in": "Ghana"
    },
    {
        "code": "GIP",
        "name": "Gibraltar Pound",
        "symbol": "£",
        "numeric": "292",
        "used_in": "Gibraltar"
    },
    {
        "code": "GMD",
        "name": "Dalasi",
        "symbol": "D",
        "numeric": "270",
        "used_in": "Gambia"
    },
    {
        "code": "GNF",
        "name": "Guinean Franc",
        "symbol": "FG",
        "numeric": "324",
        "used_in": "Guinea"
    },
    {
        "code": "GTQ",
        "name": "Quetzal",
        "symbol": "Q",
        "numeric": "320",
        "used_in": "Guatemala"
    },
    {
        "code": "GYD",
        "name": "Guyana Dollar",
        "symbol": "$",
        "numeric": "328",
        "used_in": "Guyana"
    },
    {
        "code": "HKD",
        "name": "Hong Kong Dollar",
        "symbol": "$",
        "numeric": "344",
        "used_in": "Hong Kong"
    },
    {
        "code": "HNL",
        "name": "Lempira",
        "symbol": "L",
        "numeric": "340",
        "used_in": "Honduras"
    },
    {
        "code": "HRK",
        "name": "Kuna",
        "symbol": "kn",
        "numeric": "191",
        "used_in": "Croatia (historical, replaced by EUR)"
    },
    {
        "code": "HTG",
        "name": "Gourde",
        "symbol": "G",
        "numeric": "332",
        "used_in": "Haiti"
    },
    {
        "code": "HUF",
        "name": "Forint",
        "symbol": "Ft",
        "numeric": "348",
        "used_in": "Hungary"
    },
    {
        "code": "IDR",
        "name": "Rupiah",
        "symbol": "Rp",
        "numeric": "360",
        "used_in": "Indonesia"
    },
    {
        "code": "ILS",
        "name": "New Israeli Sheqel",
        "symbol": "₪",
        "numeric": "376",
        "used_in": "Israel"
    },
    {
        "code": "INR",
        "name": "Indian Rupee",
        "symbol": "₹",
        "numeric": "356",
        "used_in": "India"
    },
    {
        "code": "IQD",
        "name": "Iraqi Dinar",
        "symbol": "ع.د",
        "numeric": "368",
        "used_in": "Iraq"
    },
    {
        "code": "IRR",
        "name": "Iranian Rial",
        "symbol": "﷼",
        "numeric": "364",
        "used_in": "Iran"
    },
    {
        "code": "ISK",
        "name": "Iceland Krona",
        "symbol": "kr",
        "numeric": "352",
        "used_in": "Iceland"
    },
    {
        "code": "JMD",
        "name": "Jamaican Dollar",
        "symbol": "$",
        "numeric": "388",
        "used_in": "Jamaica"
    },
    {
        "code": "JOD",
        "name": "Jordanian Dinar",
        "symbol": "د.ا",
        "numeric": "400",
        "used_in": "Jordan"
    },
    {
        "code": "JPY",
        "name": "Yen",
        "symbol": "¥",
        "numeric": "392",
        "used_in": "Japan"
    },
    {
        "code": "KES",
        "name": "Kenyan Shilling",
        "symbol": "KSh",
        "numeric": "404",
        "used_in": "Kenya"
    },
    {
        "code": "KGS",
        "name": "Som",
        "symbol": "с",
        "numeric": "417",
        "used_in": "Kyrgyzstan"
    },
    {
        "code": "KHR",
        "name": "Riel",
        "symbol": "៛",
        "numeric": "116",
        "used_in": "Cambodia"
    },
    {
        "code": "KMF",
        "name": "Comorian Franc",
        "symbol": "CF",
        "numeric": "174",
        "used_in": "Comoros"
    },
    {
        "code": "KPW",
        "name": "North Korean Won",
        "symbol": "₩",
        "numeric": "408",
        "used_in": "North Korea"
    },
    {
        "code": "KRW",
        "name": "Won",
        "symbol": "₩",
        "numeric": "410",
        "used_in": "South Korea"
    },
    {
        "code": "KWD",
        "name": "Kuwaiti Dinar",
        "symbol": "د.ك",
        "numeric": "414",
        "used_in": "Kuwait"
    },
    {
        "code": "KYD",
        "name": "Cayman Islands Dollar",
        "symbol": "$",
        "numeric": "136",
        "used_in": "Cayman Islands"
    },
    {
        "code": "KZT",
        "name": "Tenge",
        "symbol": "₸",
        "numeric": "398",
        "used_in": "Kazakhstan"
    },
    {
        "code": "LAK",
        "name": "Lao Kip",
        "symbol": "₭",
        "numeric": "418",
        "used_in": "Laos"
    },
    {
        "code": "LBP",
        "name": "Lebanese Pound",
        "symbol": "ل.ل",
        "numeric": "422",
        "used_in": "Lebanon"
    },
    {
        "code": "LKR",
        "name": "Sri Lanka Rupee",
        "symbol": "Rs",
        "numeric": "144",
        "used_in": "Sri Lanka"
    },
    {
        "code": "LRD",
        "name": "Liberian Dollar",
        "symbol": "$",
        "numeric": "430",
        "used_in": "Liberia"
    },
    {
        "code": "LSL",
        "name": "Loti",
        "symbol": "L",
        "numeric": "426",
        "used_in": "Lesotho"
    },
    {
        "code": "LYD",
        "name": "Libyan Dinar",
        "symbol": "ل.د",
        "numeric": "434",
        "used_in": "Libya"
    },
    {
        "code": "MAD",
        "name": "Moroccan Dirham",
        "symbol": "د.م.",
        "numeric": "504",
        "used_in": "Morocco"
    },
    {
        "code": "MDL",
        "name": "Moldovan Leu",
        "symbol": "L",
        "numeric": "498",
        "used_in": "Moldova"
    },
    {
        "code": "MGA",
        "name": "Malagasy Ariary",
        "symbol": "Ar",
        "numeric": "969",
        "used_in": "Madagascar"
    },
    {
        "code": "MKD",
        "name": "Denar",
        "symbol": "ден",
        "numeric": "807",
        "used_in": "North Macedonia"
    },
    {
        "code": "MMK",
        "name": "Kyat",
        "symbol": "K",
        "numeric": "104",
        "used_in": "Myanmar"
    },
    {
        "code": "MNT",
        "name": "Tugrik",
        "symbol": "₮",
        "numeric": "496",
        "used_in": "Mongolia"
    },
    {
        "code": "MOP",
        "name": "Pataca",
        "symbol": "MOP$",
        "numeric": "446",
        "used_in": "Macao"
    },
    {
        "code": "MRU",
        "name": "Ouguiya",
        "symbol": "UM",
        "numeric": "929",
        "used_in": "Mauritania"
    },
    {
        "code": "MUR",
        "name": "Mauritius Rupee",
        "symbol": "₨",
        "numeric": "480",
        "used_in": "Mauritius"
    },
    {
        "code": "MVR",
        "name": "Rufiyaa",
        "symbol": ".ރ",
        "numeric": "462",
        "used_in": "Maldives"
    },
    {
        "code": "MWK",
        "name": "Malawi Kwacha",
        "symbol": "MK",
        "numeric": "454",
        "used_in": "Malawi"
    },
    {
        "code": "MXN",
        "name": "Mexican Peso",
        "symbol": "$",
        "numeric": "484",
        "used_in": "Mexico"
    },
    {
        "code": "MYR",
        "name": "Malaysian Ringgit",
        "symbol": "RM",
        "numeric": "458",
        "used_in": "Malaysia"
    },
    {
        "code": "MZN",
        "name": "Mozambique Metical",
        "symbol": "MT",
        "numeric": "943",
        "used_in": "Mozambique"
    },
    {
        "code": "NAD",
        "name": "Namibia Dollar",
        "symbol": "$",
        "numeric": "516",
        "used_in": "Namibia"
    },
    {
        "code": "NGN",
        "name": "Naira",
        "symbol": "₦",
        "numeric": "566",
        "used_in": "Nigeria"
    },
    {
        "code": "NIO",
        "name": "Cordoba Oro",
        "symbol": "C$",
        "numeric": "558",
        "used_in": "Nicaragua"
    },
    {
        "code": "NOK",
        "name": "Norwegian Krone",
        "symbol": "kr",
        "numeric": "578",
        "used_in": "Norway"
    },
    {
        "code": "NPR",
        "name": "Nepalese Rupee",
        "symbol": "Rs",
        "numeric": "524",
        "used_in": "Nepal"
    },
    {
        "code": "NZD",
        "name": "New Zealand Dollar",
        "symbol": "$",
        "numeric": "554",
        "used_in": "New Zealand"
    },
    {
        "code": "OMR",
        "name": "Rial Omani",
        "symbol": "ر.ع.",
        "numeric": "512",
        "used_in": "Oman"
    },
    {
        "code": "PAB",
        "name": "Balboa",
        "symbol": "B/.",
        "numeric": "590",
        "used_in": "Panama"
    },
    {
        "code": "PEN",
        "name": "Sol",
        "symbol": "S/",
        "numeric": "604",
        "used_in": "Peru"
    },
    {
        "code": "PGK",
        "name": "Kina",
        "symbol": "K",
        "numeric": "598",
        "used_in": "Papua New Guinea"
    },
    {
        "code": "PHP",
        "name": "Philippine Peso",
        "symbol": "₱",
        "numeric": "608",
        "used_in": "Philippines"
    },
    {
        "code": "PKR",
        "name": "Pakistan Rupee",
        "symbol": "₨",
        "numeric": "586",
        "used_in": "Pakistan"
    },
    {
        "code": "PLN",
        "name": "Zloty",
        "symbol": "zł",
        "numeric": "985",
        "used_in": "Poland"
    },
    {
        "code": "PYG",
        "name": "Guarani",
        "symbol": "₲",
        "numeric": "600",
        "used_in": "Paraguay"
    },
    {
        "code": "QAR",
        "name": "Qatari Rial",
        "symbol": "ر.ق",
        "numeric": "634",
        "used_in": "Qatar"
    },
    {
        "code": "RON",
        "name": "Romanian Leu",
        "symbol": "lei",
        "numeric": "946",
        "used_in": "Romania"
    },
    {
        "code": "RSD",
        "name": "Serbian Dinar",
        "symbol": "дин.",
        "numeric": "941",
        "used_in": "Serbia"
    },
    {
        "code": "RUB",
        "name": "Russian Ruble",
        "symbol": "₽",
        "numeric": "643",
        "used_in": "Russia"
    },
    {
        "code": "RWF",
        "name": "Rwanda Franc",
        "symbol": "FRw",
        "numeric": "646",
        "used_in": "Rwanda"
    },
    {
        "code": "SAR",
        "name": "Saudi Riyal",
        "symbol": "ر.س",
        "numeric": "682",
        "used_in": "Saudi Arabia"
    },
    {
        "code": "SBD",
        "name": "Solomon Islands Dollar",
        "symbol": "$",
        "numeric": "090",
        "used_in": "Solomon Islands"
    },
    {
        "code": "SCR",
        "name": "Seychelles Rupee",
        "symbol": "₨",
        "numeric": "690",
        "used_in": "Seychelles"
    },
    {
        "code": "SDG",
        "name": "Sudanese Pound",
        "symbol": "ج.س.",
        "numeric": "938",
        "used_in": "Sudan"
    },
    {
        "code": "SEK",
        "name": "Swedish Krona",
        "symbol": "kr",
        "numeric": "752",
        "used_in": "Sweden"
    },
    {
        "code": "SGD",
        "name": "Singapore Dollar",
        "symbol": "$",
        "numeric": "702",
        "used_in": "Singapore"
    },
    {
        "code": "SHP",
        "name": "Saint Helena Pound",
        "symbol": "£",
        "numeric": "654",
        "used_in": "Saint Helena, Ascension"
    },
    {
        "code": "SLE",
        "name": "Leone",
        "symbol": "Le",
        "numeric": "925",
        "used_in": "Sierra Leone"
    },
    {
        "code": "SOS",
        "name": "Somali Shilling",
        "symbol": "Sh",
        "numeric": "706",
        "used_in": "Somalia"
    },
    {
        "code": "SRD",
        "name": "Surinam Dollar",
        "symbol": "$",
        "numeric": "968",
        "used_in": "Suriname"
    },
    {
        "code": "SSP",
        "name": "South Sudanese Pound",
        "symbol": "£",
        "numeric": "728",
        "used_in": "South Sudan"
    },
    {
        "code": "STN",
        "name": "Dobra",
        "symbol": "Db",
        "numeric": "930",
        "used_in": "São Tomé and Príncipe"
    },
    {
        "code": "SVC",
        "name": "El Salvador Colon",
        "symbol": "₡",
        "numeric": "222",
        "used_in": "El Salvador"
    },
    {
        "code": "SYP",
        "name": "Syrian Pound",
        "symbol": "£",
        "numeric": "760",
        "used_in": "Syria"
    },
    {
        "code": "SZL",
        "name": "Lilangeni",
        "symbol": "L",
        "numeric": "748",
        "used_in": "Eswatini"
    },
    {
        "code": "THB",
        "name": "Baht",
        "symbol": "฿",
        "numeric": "764",
        "used_in": "Thailand"
    },
    {
        "code": "TJS",
        "name": "Somoni",
        "symbol": "ЅМ",
        "numeric": "972",
        "used_in": "Tajikistan"
    },
    {
        "code": "TMT",
        "name": "Turkmenistan New Manat",
        "symbol": "m",
        "numeric": "934",
        "used_in": "Turkmenistan"
    },
    {
        "code": "TND",
        "name": "Tunisian Dinar",
        "symbol": "د.ت",
        "numeric": "788",
        "used_in": "Tunisia"
    },
    {
        "code": "TOP",
        "name": "Pa'anga",
        "symbol": "T$",
        "numeric": "776",
        "used_in": "Tonga"
    },
    {
        "code": "TRY",
        "name": "Turkish Lira",
        "symbol": "₺",
        "numeric": "949",
        "used_in": "Turkey"
    },
    {
        "code": "TTD",
        "name": "Trinidad and Tobago Dollar",
        "symbol": "$",
        "numeric": "780",
        "used_in": "Trinidad and Tobago"
    },
    {
        "code": "TWD",
        "name": "New Taiwan Dollar",
        "symbol": "NT$",
        "numeric": "901",
        "used_in": "Taiwan"
    },
    {
        "code": "TZS",
        "name": "Tanzanian Shilling",
        "symbol": "TSh",
        "numeric": "834",
        "used_in": "Tanzania"
    },
    {
        "code": "UAH",
        "name": "Hryvnia",
        "symbol": "₴",
        "numeric": "980",
        "used_in": "Ukraine"
    },
    {
        "code": "UGX",
        "name": "Uganda Shilling",
        "symbol": "USh",
        "numeric": "800",
        "used_in": "Uganda"
    },
    {
        "code": "USD",
        "name": "US Dollar",
        "symbol": "$",
        "numeric": "840",
        "used_in": "United States"
    },
    {
        "code": "UYU",
        "name": "Peso Uruguayo",
        "symbol": "$",
        "numeric": "858",
        "used_in": "Uruguay"
    },
    {
        "code": "UZS",
        "name": "Uzbekistan Sum",
        "symbol": "so'm",
        "numeric": "860",
        "used_in": "Uzbekistan"
    },
    {
        "code": "VED",
        "name": "Bolívar Soberano",
        "symbol": "Bs.",
        "numeric": "926",
        "used_in": "Venezuela"
    },
    {
        "code": "VES",
        "name": "Bolívar Soberano",
        "symbol": "Bs.",
        "numeric": "928",
        "used_in": "Venezuela"
    },
    {
        "code": "VND",
        "name": "Dong",
        "symbol": "₫",
        "numeric": "704",
        "used_in": "Vietnam"
    },
    {
        "code": "VUV",
        "name": "Vatu",
        "symbol": "VT",
        "numeric": "548",
        "used_in": "Vanuatu"
    },
    {
        "code": "WST",
        "name": "Tala",
        "symbol": "$",
        "numeric": "882",
        "used_in": "Samoa"
    },
    {
        "code": "XAF",
        "name": "CFA Franc BEAC",
        "symbol": "FCFA",
        "numeric": "950",
        "used_in": "Central African States (Cameroon, Chad, etc.)"
    },
    {
        "code": "XCD",
        "name": "East Caribbean Dollar",
        "symbol": "$",
        "numeric": "951",
        "used_in": "Organisation of Eastern Caribbean States"
    },
    {
        "code": "XCG",
        "name": "Caribbean Guilder",
        "symbol": "ƒ",
        "numeric": "532",
        "used_in": "Curaçao, Sint Maarten"
    },
    {
        "code": "XOF",
        "name": "CFA Franc BCEAO",
        "symbol": "CFA",
        "numeric": "952",
        "used_in": "West African States (Senegal, Côte d'Ivoire, etc.)"
    },
    {
        "code": "XPF",
        "name": "CFP Franc",
        "symbol": "₣",
        "numeric": "953",
        "used_in": "French Polynesia, New Caledonia"
    },
    {
        "code": "YER",
        "name": "Yemeni Rial",
        "symbol": "﷼",
        "numeric": "886",
        "used_in": "Yemen"
    },
    {
        "code": "ZAR",
        "name": "Rand",
        "symbol": "R",
        "numeric": "710",
        "used_in": "South Africa"
    },
    {
        "code": "ZMW",
        "name": "Zambian Kwacha",
        "symbol": "ZK",
        "numeric": "967",
        "used_in": "Zambia"
    },
    {
        "code": "ZWG",
        "name": "Zimbabwe Gold",
        "symbol": "ZiG",
        "numeric": "924",
        "used_in": "Zimbabwe"
    }
]
